# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.serialization import FieldMetadata
from ....core.unchecked_base_model import UncheckedBaseModel


class StartOrResumeCampaignsResponseData(UncheckedBaseModel):
    message: typing.Optional[str] = None
    task_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="taskId"),
        pydantic.Field(alias="taskId", description="Internal task identifier for the queued job"),
    ] = None
    campaign_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="campaignId"),
        pydantic.Field(alias="campaignId", description="The ID of the campaign"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
