# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel


class UsagePromptTokensDetails(UncheckedBaseModel):
    cached_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    Subset of `prompt_tokens` served from prefix cache. Billed at
    the discounted rate ($0.10 / 1M vs $0.40 / 1M for fresh input).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
