# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .cancel_conversations_response import CancelConversationsResponse
    from .cancel_conversations_response_data import CancelConversationsResponseData
    from .cancel_queued_conversations_response import CancelQueuedConversationsResponse
    from .cancel_queued_conversations_response_data import CancelQueuedConversationsResponseData
    from .get_conversation_call_id_recording_download_url_response import (
        GetConversationCallIdRecordingDownloadUrlResponse,
    )
    from .get_conversation_call_id_recording_download_url_response_data import (
        GetConversationCallIdRecordingDownloadUrlResponseData,
    )
    from .list_retry_attempts_conversations_response import ListRetryAttemptsConversationsResponse
    from .list_retry_attempts_conversations_response_data import ListRetryAttemptsConversationsResponseData
_dynamic_imports: typing.Dict[str, str] = {
    "CancelConversationsResponse": ".cancel_conversations_response",
    "CancelConversationsResponseData": ".cancel_conversations_response_data",
    "CancelQueuedConversationsResponse": ".cancel_queued_conversations_response",
    "CancelQueuedConversationsResponseData": ".cancel_queued_conversations_response_data",
    "GetConversationCallIdRecordingDownloadUrlResponse": ".get_conversation_call_id_recording_download_url_response",
    "GetConversationCallIdRecordingDownloadUrlResponseData": ".get_conversation_call_id_recording_download_url_response_data",
    "ListRetryAttemptsConversationsResponse": ".list_retry_attempts_conversations_response",
    "ListRetryAttemptsConversationsResponseData": ".list_retry_attempts_conversations_response_data",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CancelConversationsResponse",
    "CancelConversationsResponseData",
    "CancelQueuedConversationsResponse",
    "CancelQueuedConversationsResponseData",
    "GetConversationCallIdRecordingDownloadUrlResponse",
    "GetConversationCallIdRecordingDownloadUrlResponseData",
    "ListRetryAttemptsConversationsResponse",
    "ListRetryAttemptsConversationsResponseData",
]
