# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ..types.post_call_analytics_config import PostCallAnalyticsConfig
from ..types.single_prompt_config import SinglePromptConfig
from ..types.test_call_request_mode import TestCallRequestMode
from ..types.workflow_type import WorkflowType
from .raw_client import AsyncRawAgentVersioningDraftsClient, RawAgentVersioningDraftsClient
from .types.create_draft_agent_versioning_drafts_response import CreateDraftAgentVersioningDraftsResponse
from .types.discard_draft_agent_versioning_drafts_response import DiscardDraftAgentVersioningDraftsResponse
from .types.draft_config_request_background_sound import DraftConfigRequestBackgroundSound
from .types.draft_config_request_slm_model import DraftConfigRequestSlmModel
from .types.get_agent_id_drafts_draft_id_diff_response import GetAgentIdDraftsDraftIdDiffResponse
from .types.get_agent_id_drafts_draft_id_response import GetAgentIdDraftsDraftIdResponse
from .types.get_agent_id_drafts_response import GetAgentIdDraftsResponse
from .types.post_agent_id_drafts_draft_id_test_call_response import PostAgentIdDraftsDraftIdTestCallResponse
from .types.publish_draft_agent_versioning_drafts_response import PublishDraftAgentVersioningDraftsResponse
from .types.rename_draft_agent_versioning_drafts_response import RenameDraftAgentVersioningDraftsResponse
from .types.update_draft_config_agent_versioning_drafts_response import UpdateDraftConfigAgentVersioningDraftsResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AgentVersioningDraftsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgentVersioningDraftsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAgentVersioningDraftsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgentVersioningDraftsClient
        """
        return self._raw_client

    def list_active_drafts(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetAgentIdDraftsResponse:
        """
        List all active (non-discarded) drafts for an agent.

        Parameters
        ----------
        id : str
            The agent ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAgentIdDraftsResponse
            Successful response

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.agent_versioning_drafts.list_active_drafts(
            id="60d0fe4f5311236168a109ca",
        )
        """
        _response = self._raw_client.list_active_drafts(id, request_options=request_options)
        return _response.data

    def create_draft(
        self,
        id: str,
        *,
        source_version_id: typing.Optional[str] = OMIT,
        source_draft_id: typing.Optional[str] = OMIT,
        draft_name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateDraftAgentVersioningDraftsResponse:
        """
        Create a new draft from an existing published version or another draft. At least one of sourceVersionId or sourceDraftId is required (both may be sent simultaneously).

        Parameters
        ----------
        id : str
            The agent ID

        source_version_id : typing.Optional[str]
            ID of a published version to branch from. Must be a valid MongoDB ObjectId (24-char hex).
            Sending a non-ObjectId format returns 400.

        source_draft_id : typing.Optional[str]
            ID of an existing draft to branch from

        draft_name : typing.Optional[str]
            Optional name for the draft (1–100 characters)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateDraftAgentVersioningDraftsResponse
            Draft created successfully

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.agent_versioning_drafts.create_draft(
            id="60d0fe4f5311236168a109ca",
        )
        """
        _response = self._raw_client.create_draft(
            id,
            source_version_id=source_version_id,
            source_draft_id=source_draft_id,
            draft_name=draft_name,
            request_options=request_options,
        )
        return _response.data

    def get_draft_detail(
        self,
        id: str,
        draft_id: str,
        *,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetAgentIdDraftsDraftIdResponse:
        """
        Returns the latest revision of a draft along with its edit history.

        Parameters
        ----------
        id : str
            The agent ID

        draft_id : str
            The draft ID

        limit : typing.Optional[int]
            Max number of edit history entries to return (1-100)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAgentIdDraftsDraftIdResponse
            Successful response

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.agent_versioning_drafts.get_draft_detail(
            id="60d0fe4f5311236168a109ca",
            draft_id="draftId",
        )
        """
        _response = self._raw_client.get_draft_detail(id, draft_id, limit=limit, request_options=request_options)
        return _response.data

    def discard_draft(
        self, id: str, draft_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DiscardDraftAgentVersioningDraftsResponse:
        """
        Discard (soft-delete) a draft. Only the draft creator or an admin can discard.

        Parameters
        ----------
        id : str
            The agent ID

        draft_id : str
            The draft ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DiscardDraftAgentVersioningDraftsResponse
            Draft discarded successfully

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.agent_versioning_drafts.discard_draft(
            id="60d0fe4f5311236168a109ca",
            draft_id="draftId",
        )
        """
        _response = self._raw_client.discard_draft(id, draft_id, request_options=request_options)
        return _response.data

    def rename_draft(
        self, id: str, draft_id: str, *, draft_name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> RenameDraftAgentVersioningDraftsResponse:
        """
        Rename a draft. For config changes, use PATCH /agent/{id}/drafts/{draftId}/config instead.

        Parameters
        ----------
        id : str
            The agent ID

        draft_id : str
            The draft ID

        draft_name : str
            New name for the draft (1–100 characters)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RenameDraftAgentVersioningDraftsResponse
            Draft renamed successfully

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.agent_versioning_drafts.rename_draft(
            id="60d0fe4f5311236168a109ca",
            draft_id="draftId",
            draft_name="draftName",
        )
        """
        _response = self._raw_client.rename_draft(id, draft_id, draft_name=draft_name, request_options=request_options)
        return _response.data

    def get_draft_diff(
        self,
        id: str,
        draft_id: str,
        *,
        compare_to: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetAgentIdDraftsDraftIdDiffResponse:
        """
        Compare a draft against its source version or another specified version.

        Parameters
        ----------
        id : str
            The agent ID

        draft_id : str
            The draft ID

        compare_to : typing.Optional[str]
            Version ID to compare against. If omitted, compares against the source version.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAgentIdDraftsDraftIdDiffResponse
            Diff returned successfully

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.agent_versioning_drafts.get_draft_diff(
            id="60d0fe4f5311236168a109ca",
            draft_id="draftId",
        )
        """
        _response = self._raw_client.get_draft_diff(
            id, draft_id, compare_to=compare_to, request_options=request_options
        )
        return _response.data

    def publish_draft(
        self,
        id: str,
        draft_id: str,
        *,
        label: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        activate: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublishDraftAgentVersioningDraftsResponse:
        """
        Publish a draft as a new versioned release. Optionally activate it immediately.

        Parameters
        ----------
        id : str
            The agent ID

        draft_id : str
            The draft ID

        label : typing.Optional[str]
            Label for the published version

        description : typing.Optional[str]
            Description of the published version

        activate : typing.Optional[bool]
            Whether to immediately activate the version after publishing

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublishDraftAgentVersioningDraftsResponse
            Draft published as a new version

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.agent_versioning_drafts.publish_draft(
            id="60d0fe4f5311236168a109ca",
            draft_id="draftId",
        )
        """
        _response = self._raw_client.publish_draft(
            id, draft_id, label=label, description=description, activate=activate, request_options=request_options
        )
        return _response.data

    def test_call_with_draft_config(
        self,
        id: str,
        draft_id: str,
        *,
        mode: typing.Optional[TestCallRequestMode] = OMIT,
        to_phone: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostAgentIdDraftsDraftIdTestCallResponse:
        """
        Initiate a test call using the draft's resolved configuration.

        Parameters
        ----------
        id : str
            The agent ID

        draft_id : str
            The draft ID

        mode : typing.Optional[TestCallRequestMode]
            Test call mode. Defaults to `webcall` when omitted.

        to_phone : typing.Optional[str]
            Phone number to call. Required only when `mode` is `telephony`. Omit for `webcall` and `chat`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostAgentIdDraftsDraftIdTestCallResponse
            Test call initiated

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.agent_versioning_drafts.test_call_with_draft_config(
            id="60d0fe4f5311236168a109ca",
            draft_id="draftId",
        )
        """
        _response = self._raw_client.test_call_with_draft_config(
            id, draft_id, mode=mode, to_phone=to_phone, request_options=request_options
        )
        return _response.data

    def update_draft_config(
        self,
        id: str,
        draft_id: str,
        *,
        single_prompt_config: typing.Optional[SinglePromptConfig] = OMIT,
        post_call_analytics_config: typing.Optional[PostCallAnalyticsConfig] = OMIT,
        language: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        synthesizer: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        slm_model: typing.Optional[DraftConfigRequestSlmModel] = OMIT,
        transcriber_type: typing.Optional[str] = OMIT,
        custom_llm_web_socket_url: typing.Optional[str] = OMIT,
        widget_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        default_variables: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        pre_call_api: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        global_prompt: typing.Optional[str] = OMIT,
        global_knowledge_base_id: typing.Optional[str] = OMIT,
        first_message: typing.Optional[str] = OMIT,
        allow_interruptions: typing.Optional[bool] = OMIT,
        wait_for_user_to_speak_first: typing.Optional[bool] = OMIT,
        mute_user_until_first_bot_response: typing.Optional[bool] = OMIT,
        interruption_backoff_timer: typing.Optional[float] = OMIT,
        background_sound: typing.Optional[DraftConfigRequestBackgroundSound] = OMIT,
        smart_turn_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        voice_detection_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        voice_mail_detection_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        denoising_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        redaction_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        pronunciation_dicts: typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]] = OMIT,
        llm_idle_timeout_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        session_timeout_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        workflow_type: typing.Optional[WorkflowType] = OMIT,
        timezone: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        call_disposition_config: typing.Optional[str] = OMIT,
        enable_style_guide: typing.Optional[bool] = OMIT,
        speech_formatting: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateDraftConfigAgentVersioningDraftsResponse:
        """
        Update the configuration of a draft. This single endpoint is how every
        agent-level config field is changed: prompt, tools, voice, language,
        **post-call analytics (disposition metrics)**, and more. There is no
        standalone post-call-analytics endpoint — it lives here as the
        `postCallAnalyticsConfig` body field.

        ## Post-Call Analytics

        Pass a `postCallAnalyticsConfig` object to configure disposition
        metrics (STRING, BOOLEAN, INTEGER, ENUM, DATETIME) that are
        automatically extracted from each completed call, along with the
        `useInternalAnalyticsModel` and `useReasoningModel` flags. See the
        [Post-Call Metrics guide](/atoms/atoms-platform/features/post-call-metrics) for a
        full Python walkthrough and disposition metric schema reference.

        ## Full payload

        Accepts the full agent-shaped config payload (language, synthesizer,
        slmModel, defaultVariables, preCallAPI, etc.) plus two draft-specific
        fields:

        - `singlePromptConfig` — prompt and tools (end_call, transfer_call,
          api_call, extract_dynamic_variables, knowledge_base_search).
        - `postCallAnalyticsConfig` — disposition metrics + analytics/
          reasoning model flags.

        Each PATCH increments the draft's revision counter. Config is not
        live until the draft is published and activated (see
        `/drafts/{draftId}/publish` and `/versions/{versionId}/activate`).

        Parameters
        ----------
        id : str
            The agent ID

        draft_id : str
            The draft ID

        single_prompt_config : typing.Optional[SinglePromptConfig]

        post_call_analytics_config : typing.Optional[PostCallAnalyticsConfig]

        language : typing.Optional[typing.Dict[str, typing.Any]]
            Language configuration. See CreateAgentRequest for full shape.

        synthesizer : typing.Optional[typing.Dict[str, typing.Any]]
            Synthesizer (TTS) configuration. See CreateAgentRequest for full shape.

        slm_model : typing.Optional[DraftConfigRequestSlmModel]
            LLM model for this draft

        transcriber_type : typing.Optional[str]
            STT engine to use for this draft

        custom_llm_web_socket_url : typing.Optional[str]
            Custom LLM WebSocket URL (overrides slmModel)

        widget_config : typing.Optional[typing.Dict[str, typing.Any]]
            Widget configuration for chat-mode agents

        default_variables : typing.Optional[typing.Dict[str, typing.Any]]
            Default prompt variables

        pre_call_api : typing.Optional[typing.Dict[str, typing.Any]]
            Pre-call API configuration. See CreateAgentRequest for full shape.

        global_prompt : typing.Optional[str]
            Global prompt for workflow_graph agents (max 4000 characters)

        global_knowledge_base_id : typing.Optional[str]
            Knowledge base ID to attach to this draft

        first_message : typing.Optional[str]
            Opening message for this draft

        allow_interruptions : typing.Optional[bool]

        wait_for_user_to_speak_first : typing.Optional[bool]

        mute_user_until_first_bot_response : typing.Optional[bool]

        interruption_backoff_timer : typing.Optional[float]

        background_sound : typing.Optional[DraftConfigRequestBackgroundSound]

        smart_turn_config : typing.Optional[typing.Dict[str, typing.Any]]

        voice_detection_config : typing.Optional[typing.Dict[str, typing.Any]]

        voice_mail_detection_config : typing.Optional[typing.Dict[str, typing.Any]]

        denoising_config : typing.Optional[typing.Dict[str, typing.Any]]

        redaction_config : typing.Optional[typing.Dict[str, typing.Any]]

        pronunciation_dicts : typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]]

        llm_idle_timeout_config : typing.Optional[typing.Dict[str, typing.Any]]

        session_timeout_config : typing.Optional[typing.Dict[str, typing.Any]]

        workflow_type : typing.Optional[WorkflowType]

        timezone : typing.Optional[typing.Dict[str, typing.Any]]

        call_disposition_config : typing.Optional[str]

        enable_style_guide : typing.Optional[bool]

        speech_formatting : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateDraftConfigAgentVersioningDraftsResponse
            Draft config updated successfully

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.agent_versioning_drafts.update_draft_config(
            id="60d0fe4f5311236168a109ca",
            draft_id="draftId",
        )
        """
        _response = self._raw_client.update_draft_config(
            id,
            draft_id,
            single_prompt_config=single_prompt_config,
            post_call_analytics_config=post_call_analytics_config,
            language=language,
            synthesizer=synthesizer,
            slm_model=slm_model,
            transcriber_type=transcriber_type,
            custom_llm_web_socket_url=custom_llm_web_socket_url,
            widget_config=widget_config,
            default_variables=default_variables,
            pre_call_api=pre_call_api,
            global_prompt=global_prompt,
            global_knowledge_base_id=global_knowledge_base_id,
            first_message=first_message,
            allow_interruptions=allow_interruptions,
            wait_for_user_to_speak_first=wait_for_user_to_speak_first,
            mute_user_until_first_bot_response=mute_user_until_first_bot_response,
            interruption_backoff_timer=interruption_backoff_timer,
            background_sound=background_sound,
            smart_turn_config=smart_turn_config,
            voice_detection_config=voice_detection_config,
            voice_mail_detection_config=voice_mail_detection_config,
            denoising_config=denoising_config,
            redaction_config=redaction_config,
            pronunciation_dicts=pronunciation_dicts,
            llm_idle_timeout_config=llm_idle_timeout_config,
            session_timeout_config=session_timeout_config,
            workflow_type=workflow_type,
            timezone=timezone,
            call_disposition_config=call_disposition_config,
            enable_style_guide=enable_style_guide,
            speech_formatting=speech_formatting,
            request_options=request_options,
        )
        return _response.data


class AsyncAgentVersioningDraftsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgentVersioningDraftsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAgentVersioningDraftsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgentVersioningDraftsClient
        """
        return self._raw_client

    async def list_active_drafts(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetAgentIdDraftsResponse:
        """
        List all active (non-discarded) drafts for an agent.

        Parameters
        ----------
        id : str
            The agent ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAgentIdDraftsResponse
            Successful response

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.agent_versioning_drafts.list_active_drafts(
                id="60d0fe4f5311236168a109ca",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_active_drafts(id, request_options=request_options)
        return _response.data

    async def create_draft(
        self,
        id: str,
        *,
        source_version_id: typing.Optional[str] = OMIT,
        source_draft_id: typing.Optional[str] = OMIT,
        draft_name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateDraftAgentVersioningDraftsResponse:
        """
        Create a new draft from an existing published version or another draft. At least one of sourceVersionId or sourceDraftId is required (both may be sent simultaneously).

        Parameters
        ----------
        id : str
            The agent ID

        source_version_id : typing.Optional[str]
            ID of a published version to branch from. Must be a valid MongoDB ObjectId (24-char hex).
            Sending a non-ObjectId format returns 400.

        source_draft_id : typing.Optional[str]
            ID of an existing draft to branch from

        draft_name : typing.Optional[str]
            Optional name for the draft (1–100 characters)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateDraftAgentVersioningDraftsResponse
            Draft created successfully

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.agent_versioning_drafts.create_draft(
                id="60d0fe4f5311236168a109ca",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_draft(
            id,
            source_version_id=source_version_id,
            source_draft_id=source_draft_id,
            draft_name=draft_name,
            request_options=request_options,
        )
        return _response.data

    async def get_draft_detail(
        self,
        id: str,
        draft_id: str,
        *,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetAgentIdDraftsDraftIdResponse:
        """
        Returns the latest revision of a draft along with its edit history.

        Parameters
        ----------
        id : str
            The agent ID

        draft_id : str
            The draft ID

        limit : typing.Optional[int]
            Max number of edit history entries to return (1-100)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAgentIdDraftsDraftIdResponse
            Successful response

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.agent_versioning_drafts.get_draft_detail(
                id="60d0fe4f5311236168a109ca",
                draft_id="draftId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_draft_detail(id, draft_id, limit=limit, request_options=request_options)
        return _response.data

    async def discard_draft(
        self, id: str, draft_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DiscardDraftAgentVersioningDraftsResponse:
        """
        Discard (soft-delete) a draft. Only the draft creator or an admin can discard.

        Parameters
        ----------
        id : str
            The agent ID

        draft_id : str
            The draft ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DiscardDraftAgentVersioningDraftsResponse
            Draft discarded successfully

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.agent_versioning_drafts.discard_draft(
                id="60d0fe4f5311236168a109ca",
                draft_id="draftId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.discard_draft(id, draft_id, request_options=request_options)
        return _response.data

    async def rename_draft(
        self, id: str, draft_id: str, *, draft_name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> RenameDraftAgentVersioningDraftsResponse:
        """
        Rename a draft. For config changes, use PATCH /agent/{id}/drafts/{draftId}/config instead.

        Parameters
        ----------
        id : str
            The agent ID

        draft_id : str
            The draft ID

        draft_name : str
            New name for the draft (1–100 characters)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RenameDraftAgentVersioningDraftsResponse
            Draft renamed successfully

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.agent_versioning_drafts.rename_draft(
                id="60d0fe4f5311236168a109ca",
                draft_id="draftId",
                draft_name="draftName",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.rename_draft(
            id, draft_id, draft_name=draft_name, request_options=request_options
        )
        return _response.data

    async def get_draft_diff(
        self,
        id: str,
        draft_id: str,
        *,
        compare_to: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetAgentIdDraftsDraftIdDiffResponse:
        """
        Compare a draft against its source version or another specified version.

        Parameters
        ----------
        id : str
            The agent ID

        draft_id : str
            The draft ID

        compare_to : typing.Optional[str]
            Version ID to compare against. If omitted, compares against the source version.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAgentIdDraftsDraftIdDiffResponse
            Diff returned successfully

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.agent_versioning_drafts.get_draft_diff(
                id="60d0fe4f5311236168a109ca",
                draft_id="draftId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_draft_diff(
            id, draft_id, compare_to=compare_to, request_options=request_options
        )
        return _response.data

    async def publish_draft(
        self,
        id: str,
        draft_id: str,
        *,
        label: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        activate: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublishDraftAgentVersioningDraftsResponse:
        """
        Publish a draft as a new versioned release. Optionally activate it immediately.

        Parameters
        ----------
        id : str
            The agent ID

        draft_id : str
            The draft ID

        label : typing.Optional[str]
            Label for the published version

        description : typing.Optional[str]
            Description of the published version

        activate : typing.Optional[bool]
            Whether to immediately activate the version after publishing

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublishDraftAgentVersioningDraftsResponse
            Draft published as a new version

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.agent_versioning_drafts.publish_draft(
                id="60d0fe4f5311236168a109ca",
                draft_id="draftId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.publish_draft(
            id, draft_id, label=label, description=description, activate=activate, request_options=request_options
        )
        return _response.data

    async def test_call_with_draft_config(
        self,
        id: str,
        draft_id: str,
        *,
        mode: typing.Optional[TestCallRequestMode] = OMIT,
        to_phone: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostAgentIdDraftsDraftIdTestCallResponse:
        """
        Initiate a test call using the draft's resolved configuration.

        Parameters
        ----------
        id : str
            The agent ID

        draft_id : str
            The draft ID

        mode : typing.Optional[TestCallRequestMode]
            Test call mode. Defaults to `webcall` when omitted.

        to_phone : typing.Optional[str]
            Phone number to call. Required only when `mode` is `telephony`. Omit for `webcall` and `chat`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostAgentIdDraftsDraftIdTestCallResponse
            Test call initiated

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.agent_versioning_drafts.test_call_with_draft_config(
                id="60d0fe4f5311236168a109ca",
                draft_id="draftId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.test_call_with_draft_config(
            id, draft_id, mode=mode, to_phone=to_phone, request_options=request_options
        )
        return _response.data

    async def update_draft_config(
        self,
        id: str,
        draft_id: str,
        *,
        single_prompt_config: typing.Optional[SinglePromptConfig] = OMIT,
        post_call_analytics_config: typing.Optional[PostCallAnalyticsConfig] = OMIT,
        language: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        synthesizer: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        slm_model: typing.Optional[DraftConfigRequestSlmModel] = OMIT,
        transcriber_type: typing.Optional[str] = OMIT,
        custom_llm_web_socket_url: typing.Optional[str] = OMIT,
        widget_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        default_variables: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        pre_call_api: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        global_prompt: typing.Optional[str] = OMIT,
        global_knowledge_base_id: typing.Optional[str] = OMIT,
        first_message: typing.Optional[str] = OMIT,
        allow_interruptions: typing.Optional[bool] = OMIT,
        wait_for_user_to_speak_first: typing.Optional[bool] = OMIT,
        mute_user_until_first_bot_response: typing.Optional[bool] = OMIT,
        interruption_backoff_timer: typing.Optional[float] = OMIT,
        background_sound: typing.Optional[DraftConfigRequestBackgroundSound] = OMIT,
        smart_turn_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        voice_detection_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        voice_mail_detection_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        denoising_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        redaction_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        pronunciation_dicts: typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]] = OMIT,
        llm_idle_timeout_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        session_timeout_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        workflow_type: typing.Optional[WorkflowType] = OMIT,
        timezone: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        call_disposition_config: typing.Optional[str] = OMIT,
        enable_style_guide: typing.Optional[bool] = OMIT,
        speech_formatting: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateDraftConfigAgentVersioningDraftsResponse:
        """
        Update the configuration of a draft. This single endpoint is how every
        agent-level config field is changed: prompt, tools, voice, language,
        **post-call analytics (disposition metrics)**, and more. There is no
        standalone post-call-analytics endpoint — it lives here as the
        `postCallAnalyticsConfig` body field.

        ## Post-Call Analytics

        Pass a `postCallAnalyticsConfig` object to configure disposition
        metrics (STRING, BOOLEAN, INTEGER, ENUM, DATETIME) that are
        automatically extracted from each completed call, along with the
        `useInternalAnalyticsModel` and `useReasoningModel` flags. See the
        [Post-Call Metrics guide](/atoms/atoms-platform/features/post-call-metrics) for a
        full Python walkthrough and disposition metric schema reference.

        ## Full payload

        Accepts the full agent-shaped config payload (language, synthesizer,
        slmModel, defaultVariables, preCallAPI, etc.) plus two draft-specific
        fields:

        - `singlePromptConfig` — prompt and tools (end_call, transfer_call,
          api_call, extract_dynamic_variables, knowledge_base_search).
        - `postCallAnalyticsConfig` — disposition metrics + analytics/
          reasoning model flags.

        Each PATCH increments the draft's revision counter. Config is not
        live until the draft is published and activated (see
        `/drafts/{draftId}/publish` and `/versions/{versionId}/activate`).

        Parameters
        ----------
        id : str
            The agent ID

        draft_id : str
            The draft ID

        single_prompt_config : typing.Optional[SinglePromptConfig]

        post_call_analytics_config : typing.Optional[PostCallAnalyticsConfig]

        language : typing.Optional[typing.Dict[str, typing.Any]]
            Language configuration. See CreateAgentRequest for full shape.

        synthesizer : typing.Optional[typing.Dict[str, typing.Any]]
            Synthesizer (TTS) configuration. See CreateAgentRequest for full shape.

        slm_model : typing.Optional[DraftConfigRequestSlmModel]
            LLM model for this draft

        transcriber_type : typing.Optional[str]
            STT engine to use for this draft

        custom_llm_web_socket_url : typing.Optional[str]
            Custom LLM WebSocket URL (overrides slmModel)

        widget_config : typing.Optional[typing.Dict[str, typing.Any]]
            Widget configuration for chat-mode agents

        default_variables : typing.Optional[typing.Dict[str, typing.Any]]
            Default prompt variables

        pre_call_api : typing.Optional[typing.Dict[str, typing.Any]]
            Pre-call API configuration. See CreateAgentRequest for full shape.

        global_prompt : typing.Optional[str]
            Global prompt for workflow_graph agents (max 4000 characters)

        global_knowledge_base_id : typing.Optional[str]
            Knowledge base ID to attach to this draft

        first_message : typing.Optional[str]
            Opening message for this draft

        allow_interruptions : typing.Optional[bool]

        wait_for_user_to_speak_first : typing.Optional[bool]

        mute_user_until_first_bot_response : typing.Optional[bool]

        interruption_backoff_timer : typing.Optional[float]

        background_sound : typing.Optional[DraftConfigRequestBackgroundSound]

        smart_turn_config : typing.Optional[typing.Dict[str, typing.Any]]

        voice_detection_config : typing.Optional[typing.Dict[str, typing.Any]]

        voice_mail_detection_config : typing.Optional[typing.Dict[str, typing.Any]]

        denoising_config : typing.Optional[typing.Dict[str, typing.Any]]

        redaction_config : typing.Optional[typing.Dict[str, typing.Any]]

        pronunciation_dicts : typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]]

        llm_idle_timeout_config : typing.Optional[typing.Dict[str, typing.Any]]

        session_timeout_config : typing.Optional[typing.Dict[str, typing.Any]]

        workflow_type : typing.Optional[WorkflowType]

        timezone : typing.Optional[typing.Dict[str, typing.Any]]

        call_disposition_config : typing.Optional[str]

        enable_style_guide : typing.Optional[bool]

        speech_formatting : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateDraftConfigAgentVersioningDraftsResponse
            Draft config updated successfully

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.agent_versioning_drafts.update_draft_config(
                id="60d0fe4f5311236168a109ca",
                draft_id="draftId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_draft_config(
            id,
            draft_id,
            single_prompt_config=single_prompt_config,
            post_call_analytics_config=post_call_analytics_config,
            language=language,
            synthesizer=synthesizer,
            slm_model=slm_model,
            transcriber_type=transcriber_type,
            custom_llm_web_socket_url=custom_llm_web_socket_url,
            widget_config=widget_config,
            default_variables=default_variables,
            pre_call_api=pre_call_api,
            global_prompt=global_prompt,
            global_knowledge_base_id=global_knowledge_base_id,
            first_message=first_message,
            allow_interruptions=allow_interruptions,
            wait_for_user_to_speak_first=wait_for_user_to_speak_first,
            mute_user_until_first_bot_response=mute_user_until_first_bot_response,
            interruption_backoff_timer=interruption_backoff_timer,
            background_sound=background_sound,
            smart_turn_config=smart_turn_config,
            voice_detection_config=voice_detection_config,
            voice_mail_detection_config=voice_mail_detection_config,
            denoising_config=denoising_config,
            redaction_config=redaction_config,
            pronunciation_dicts=pronunciation_dicts,
            llm_idle_timeout_config=llm_idle_timeout_config,
            session_timeout_config=session_timeout_config,
            workflow_type=workflow_type,
            timezone=timezone,
            call_disposition_config=call_disposition_config,
            enable_style_guide=enable_style_guide,
            speech_formatting=speech_formatting,
            request_options=request_options,
        )
        return _response.data
