# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.serialization import FieldMetadata
from ....core.unchecked_base_model import UncheckedBaseModel
from .tts_request_message_language import TtsRequestMessageLanguage
from .tts_request_message_model import TtsRequestMessageModel
from .tts_request_message_number_pronunciation_language import TtsRequestMessageNumberPronunciationLanguage


class TtsRequestMessage(UncheckedBaseModel):
    voice_id: str = pydantic.Field()
    """
    The ID of the voice to use. See the model card for available voices per model.
    """

    text: str = pydantic.Field()
    """
    The text to convert to speech.
    """

    model: typing.Optional[TtsRequestMessageModel] = pydantic.Field(default=None)
    """
    TTS model to route the request to. Controls which model pool
    serves this synthesis.
    
    - `lightning_v3.1` (default) — standard Lightning v3.1.
    - `lightning_v3.1_pro` — Lightning v3.1 Pro pool with a
      curated voice catalog. See the
      [Pro model card](/models/model-cards/text-to-speech/lightning-v-3-1-pro).
    
    Same concurrency and latency profile across both. Other
    request fields behave identically.
    """

    max_buffer_flush_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    The maximum time (in ms) to wait for more input before generating output. It flushes when either this time is reached or enough input is received for optimal output—whichever comes first. This is useful for input streams. Defaults to 0
    """

    continue_: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="continue"),
        pydantic.Field(
            alias="continue",
            description="This setting controls whether the system should buffer and wait for more input after receiving the current one. If not set, it assumes no more input is coming.",
        ),
    ] = None
    flush: typing.Optional[bool] = pydantic.Field(default=None)
    """
    This setting controls whether the system should flush the current buffer.
    """

    complete_backoff_ms: typing.Optional[float] = pydantic.Field(default=None)
    """
    The time in ms to wait after the last chunk is sent before sending the complete response. Default is 4000ms. Maximum is 10000ms.
    """

    language: typing.Optional[TtsRequestMessageLanguage] = pydantic.Field(default=None)
    """
    Language code for synthesis. Influences pronunciation,
    number/date normalization, and phoneme selection.
    
    Each voice has its own `tags.language` set in the voice catalog —
    query `GET /waves/v1/lightning-v3.1/get_voices`. Pass a language
    the voice was trained on; passing other codes is accepted by the
    API but produces English-pronounced output.
    
    **`auto`:** routes internally based on the input text. Any
    English or Hindi voice can be used across all supported
    languages when `auto` is set; the platform handles
    language-appropriate routing without needing a code per call.
    
    **On `lightning_v3.1`** — 20 supported languages:
    - 10 European: English, Spanish, French, German, Italian, Dutch, Swedish, Portuguese, Polish, Russian
    - 10 Indic: Hindi, Marathi, Gujarati, Punjabi, Bengali, Odia, Tamil, Telugu, Kannada, Malayalam
    
    **On `lightning_v3.1_pro`** — 31 supported languages (adds 11 over base):
    - 13 European: base 10 plus Greek, Finnish, Norwegian
    - 8 Asian & Middle Eastern: Chinese, Japanese, Korean, Indonesian, Malay, Vietnamese, Turkish, Arabic
    - 10 Indic: same as base
    - Pass `en` → UK + American accented English.
    - Pass `hi` → Indian accented English + Hindi (code-switching).
    - Omit `language` → defaults to `en + hi` (mixed Indian + Western English coverage).
    """

    number_pronunciation_language: typing.Optional[TtsRequestMessageNumberPronunciationLanguage] = pydantic.Field(
        default=None
    )
    """
    Optional. Sets the language used to read out numeric content
    — numbers, currency amounts, times, and the numeric parts of
    dates and years — independently of the synthesis voice.
    Ordinary words are not translated.
    
    - If you **omit `language`**, this value also becomes the
      synthesis language: model selection and voice routing
      follow it.
    - If you **set `language` explicitly**, `language` always wins
      for synthesis and `number_pronunciation_language` only
      changes how numeric content is normalized. It works both
      ways — read numbers in Hindi under an English voice, or in
      English under a Hindi voice (tuned for Indian, often
      mixed-script, use cases).
    - Omit this field to keep the existing behaviour —
      normalization follows `language`.
    
    Note: only numeric tokens are re-spoken; the words around them
    stay in the text language. On a cross-language request names
    may also render in the target script (e.g. "Smith" →
    "स्मिथ"), which is generally the desired reading for
    native-language voices.
    
    Accepts the same language codes as `language` (including
    `auto`, `nl`, `sv`).
    """

    sample_rate: typing.Optional[int] = pydantic.Field(default=None)
    """
    Audio sample rate in Hz. Supported values: 8000, 16000, 24000, 44100
    """

    speed: typing.Optional[float] = pydantic.Field(default=None)
    """
    Speaking speed multiplier
    """

    session_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional client-provided session identifier for correlation. Only alphanumeric characters, hyphens, underscores, and dots allowed. Max 128 characters. Echoed back in responses as `external_session_id`.
    """

    request_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional client-provided request identifier for correlation. Only alphanumeric characters, hyphens, underscores, and dots allowed. Max 128 characters. Echoed back in responses as `external_request_id`.
    """

    word_timestamps: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Opt in to per-word timing events for the synthesized audio. When `true`, the server interleaves `status: "word_timestamp"` frames with the audio `chunk` frames; each carries `data: { id, word, start, end }` where `start`/`end` are floats in seconds relative to the start of the audio stream, and `word` is verbatim from the input text (un-normalized — `"$100"` stays `"$100"`, not `"one hundred dollars"`). Supported on base-queue English + Hindi voices (`meher`, `devansh`, `kartik`, `maithili`, `liam`, `avery`); other voice families silently emit no word events (audio still works). Defaults to `false` so existing integrations see no change.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
