# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawCampaignsClient, RawCampaignsClient
from .types.delete_campaign_id_response import DeleteCampaignIdResponse
from .types.get_campaign_id_response import GetCampaignIdResponse
from .types.get_campaign_request_sort_field import GetCampaignRequestSortField
from .types.get_campaign_request_sort_order import GetCampaignRequestSortOrder
from .types.get_campaign_request_status import GetCampaignRequestStatus
from .types.get_campaign_response import GetCampaignResponse
from .types.post_campaign_id_pause_response import PostCampaignIdPauseResponse
from .types.post_campaign_id_start_response import PostCampaignIdStartResponse
from .types.post_campaign_response import PostCampaignResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CampaignsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCampaignsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCampaignsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCampaignsClient
        """
        return self._raw_client

    def retrieve_all_campaigns(
        self,
        *,
        page: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        status: typing.Optional[GetCampaignRequestStatus] = None,
        search: typing.Optional[str] = None,
        sort_field: typing.Optional[GetCampaignRequestSortField] = None,
        sort_order: typing.Optional[GetCampaignRequestSortOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetCampaignResponse:
        """
        Get all campaigns for the authenticated organization.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number for pagination

        offset : typing.Optional[int]
            Number of campaigns per page

        status : typing.Optional[GetCampaignRequestStatus]
            Filter campaigns by status

        search : typing.Optional[str]
            Search campaigns by name

        sort_field : typing.Optional[GetCampaignRequestSortField]
            Field to sort by

        sort_order : typing.Optional[GetCampaignRequestSortOrder]
            Sort direction

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCampaignResponse
            A list of campaigns

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            token="YOUR_TOKEN",
        )
        client.atoms.campaigns.retrieve_all_campaigns()
        """
        _response = self._raw_client.retrieve_all_campaigns(
            page=page,
            offset=offset,
            status=status,
            search=search,
            sort_field=sort_field,
            sort_order=sort_order,
            request_options=request_options,
        )
        return _response.data

    def create_a_campaign(
        self,
        *,
        name: str,
        audience_id: str,
        agent_id: str,
        description: typing.Optional[str] = OMIT,
        phone_number_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        scheduled_at: typing.Optional[dt.datetime] = OMIT,
        max_retries: typing.Optional[int] = OMIT,
        retry_delay: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostCampaignResponse:
        """
        Create a campaign

        Parameters
        ----------
        name : str
            The name of the campaign

        audience_id : str
            The ID of the audience

        agent_id : str
            The ID of the agent

        description : typing.Optional[str]
            The description of the campaign

        phone_number_ids : typing.Optional[typing.Sequence[str]]
            Optional list of caller-ID phone number IDs to rotate across
            when placing outbound calls for this campaign. If omitted,
            the agent's default phone number is used.

        scheduled_at : typing.Optional[dt.datetime]
            Optional ISO-8601 timestamp for when the campaign should
            start dialing. Must be in the future. If provided, the
            campaign is created in `scheduled` status; otherwise it
            starts in `draft` status and must be started manually.

        max_retries : typing.Optional[int]
            Maximum number of times a failed call is retried before the
            participant is marked as failed. `0` disables retries.

        retry_delay : typing.Optional[int]
            Delay in minutes between retry attempts for a failed call.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostCampaignResponse
            Campaign created successfully. Note: the response is the raw Mongoose document — `agentId`
            and `audienceId` are plain ObjectId strings here, not nested objects as returned by GET endpoints.

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            token="YOUR_TOKEN",
        )
        client.atoms.campaigns.create_a_campaign(
            name="My Campaign",
            audience_id="60d0fe4f5311236168a109ca",
            agent_id="60d0fe4f5311236168a109ca",
        )
        """
        _response = self._raw_client.create_a_campaign(
            name=name,
            audience_id=audience_id,
            agent_id=agent_id,
            description=description,
            phone_number_ids=phone_number_ids,
            scheduled_at=scheduled_at,
            max_retries=max_retries,
            retry_delay=retry_delay,
            request_options=request_options,
        )
        return _response.data

    def get_a_campaign(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetCampaignIdResponse:
        """
        Get a campaign with detailed metrics

        Parameters
        ----------
        id : str
            The ID of the campaign

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCampaignIdResponse
            Campaign details with metrics

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            token="YOUR_TOKEN",
        )
        client.atoms.campaigns.get_a_campaign(
            id="id",
        )
        """
        _response = self._raw_client.get_a_campaign(id, request_options=request_options)
        return _response.data

    def delete_a_campaign(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteCampaignIdResponse:
        """
        Delete a campaign

        Parameters
        ----------
        id : str
            The ID of the campaign

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteCampaignIdResponse
            Campaign deleted successfully

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            token="YOUR_TOKEN",
        )
        client.atoms.campaigns.delete_a_campaign(
            id="id",
        )
        """
        _response = self._raw_client.delete_a_campaign(id, request_options=request_options)
        return _response.data

    def start_or_resume_a_campaign(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PostCampaignIdStartResponse:
        """
        Queues the campaign for processing and returns immediately — the campaign is **not** yet
        running when the 202 is returned. Poll `GET /campaign/{id}` and watch for `status: "running"`.

        This endpoint also acts as a **resume** endpoint: if the campaign is currently paused,
        calling this endpoint resumes it (`status` transitions from `paused` → `running`).

        Parameters
        ----------
        id : str
            The ID of the campaign

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostCampaignIdStartResponse
            Campaign queued for processing

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            token="YOUR_TOKEN",
        )
        client.atoms.campaigns.start_or_resume_a_campaign(
            id="id",
        )
        """
        _response = self._raw_client.start_or_resume_a_campaign(id, request_options=request_options)
        return _response.data

    def pause_a_campaign(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PostCampaignIdPauseResponse:
        """
        Queues a pause task and returns immediately — the campaign is **not** immediately paused.
        Poll `GET /campaign/{id}` and watch for `status: "paused"`.

        Parameters
        ----------
        id : str
            The ID of the campaign

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostCampaignIdPauseResponse
            Pause task queued successfully

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            token="YOUR_TOKEN",
        )
        client.atoms.campaigns.pause_a_campaign(
            id="id",
        )
        """
        _response = self._raw_client.pause_a_campaign(id, request_options=request_options)
        return _response.data


class AsyncCampaignsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCampaignsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCampaignsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCampaignsClient
        """
        return self._raw_client

    async def retrieve_all_campaigns(
        self,
        *,
        page: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        status: typing.Optional[GetCampaignRequestStatus] = None,
        search: typing.Optional[str] = None,
        sort_field: typing.Optional[GetCampaignRequestSortField] = None,
        sort_order: typing.Optional[GetCampaignRequestSortOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetCampaignResponse:
        """
        Get all campaigns for the authenticated organization.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number for pagination

        offset : typing.Optional[int]
            Number of campaigns per page

        status : typing.Optional[GetCampaignRequestStatus]
            Filter campaigns by status

        search : typing.Optional[str]
            Search campaigns by name

        sort_field : typing.Optional[GetCampaignRequestSortField]
            Field to sort by

        sort_order : typing.Optional[GetCampaignRequestSortOrder]
            Sort direction

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCampaignResponse
            A list of campaigns

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.atoms.campaigns.retrieve_all_campaigns()


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve_all_campaigns(
            page=page,
            offset=offset,
            status=status,
            search=search,
            sort_field=sort_field,
            sort_order=sort_order,
            request_options=request_options,
        )
        return _response.data

    async def create_a_campaign(
        self,
        *,
        name: str,
        audience_id: str,
        agent_id: str,
        description: typing.Optional[str] = OMIT,
        phone_number_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        scheduled_at: typing.Optional[dt.datetime] = OMIT,
        max_retries: typing.Optional[int] = OMIT,
        retry_delay: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostCampaignResponse:
        """
        Create a campaign

        Parameters
        ----------
        name : str
            The name of the campaign

        audience_id : str
            The ID of the audience

        agent_id : str
            The ID of the agent

        description : typing.Optional[str]
            The description of the campaign

        phone_number_ids : typing.Optional[typing.Sequence[str]]
            Optional list of caller-ID phone number IDs to rotate across
            when placing outbound calls for this campaign. If omitted,
            the agent's default phone number is used.

        scheduled_at : typing.Optional[dt.datetime]
            Optional ISO-8601 timestamp for when the campaign should
            start dialing. Must be in the future. If provided, the
            campaign is created in `scheduled` status; otherwise it
            starts in `draft` status and must be started manually.

        max_retries : typing.Optional[int]
            Maximum number of times a failed call is retried before the
            participant is marked as failed. `0` disables retries.

        retry_delay : typing.Optional[int]
            Delay in minutes between retry attempts for a failed call.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostCampaignResponse
            Campaign created successfully. Note: the response is the raw Mongoose document — `agentId`
            and `audienceId` are plain ObjectId strings here, not nested objects as returned by GET endpoints.

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.atoms.campaigns.create_a_campaign(
                name="My Campaign",
                audience_id="60d0fe4f5311236168a109ca",
                agent_id="60d0fe4f5311236168a109ca",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_a_campaign(
            name=name,
            audience_id=audience_id,
            agent_id=agent_id,
            description=description,
            phone_number_ids=phone_number_ids,
            scheduled_at=scheduled_at,
            max_retries=max_retries,
            retry_delay=retry_delay,
            request_options=request_options,
        )
        return _response.data

    async def get_a_campaign(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetCampaignIdResponse:
        """
        Get a campaign with detailed metrics

        Parameters
        ----------
        id : str
            The ID of the campaign

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCampaignIdResponse
            Campaign details with metrics

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.atoms.campaigns.get_a_campaign(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_a_campaign(id, request_options=request_options)
        return _response.data

    async def delete_a_campaign(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteCampaignIdResponse:
        """
        Delete a campaign

        Parameters
        ----------
        id : str
            The ID of the campaign

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteCampaignIdResponse
            Campaign deleted successfully

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.atoms.campaigns.delete_a_campaign(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_a_campaign(id, request_options=request_options)
        return _response.data

    async def start_or_resume_a_campaign(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PostCampaignIdStartResponse:
        """
        Queues the campaign for processing and returns immediately — the campaign is **not** yet
        running when the 202 is returned. Poll `GET /campaign/{id}` and watch for `status: "running"`.

        This endpoint also acts as a **resume** endpoint: if the campaign is currently paused,
        calling this endpoint resumes it (`status` transitions from `paused` → `running`).

        Parameters
        ----------
        id : str
            The ID of the campaign

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostCampaignIdStartResponse
            Campaign queued for processing

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.atoms.campaigns.start_or_resume_a_campaign(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.start_or_resume_a_campaign(id, request_options=request_options)
        return _response.data

    async def pause_a_campaign(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PostCampaignIdPauseResponse:
        """
        Queues a pause task and returns immediately — the campaign is **not** immediately paused.
        Poll `GET /campaign/{id}` and watch for `status: "paused"`.

        Parameters
        ----------
        id : str
            The ID of the campaign

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostCampaignIdPauseResponse
            Pause task queued successfully

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.atoms.campaigns.pause_a_campaign(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.pause_a_campaign(id, request_options=request_options)
        return _response.data
