# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.serialization import FieldMetadata
from ....core.unchecked_base_model import UncheckedBaseModel


class GetAttemptCohortResponseDataCohortsItem(UncheckedBaseModel):
    attempt_number: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="attemptNumber"), pydantic.Field(alias="attemptNumber")
    ] = None
    total_calls: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="totalCalls"), pydantic.Field(alias="totalCalls")
    ] = None
    answered_calls: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="answeredCalls"), pydantic.Field(alias="answeredCalls")
    ] = None
    pickup_rate: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="pickupRate"), pydantic.Field(alias="pickupRate")
    ] = None
    cumulative_answered: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="cumulativeAnswered"), pydantic.Field(alias="cumulativeAnswered")
    ] = None
    cumulative_rate: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="cumulativeRate"), pydantic.Field(alias="cumulativeRate")
    ] = None
    marginal_gain: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="marginalGain"), pydantic.Field(alias="marginalGain")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
