# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.serialization import FieldMetadata
from ....core.unchecked_base_model import UncheckedBaseModel
from ...types.analytics_date_range import AnalyticsDateRange
from .get_pickup_rate_by_number_response_data_numbers_item import GetPickupRateByNumberResponseDataNumbersItem


class GetPickupRateByNumberResponseData(UncheckedBaseModel):
    org_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="orgId"), pydantic.Field(alias="orgId")
    ] = None
    numbers: typing.Optional[typing.List[GetPickupRateByNumberResponseDataNumbersItem]] = None
    period: typing.Optional[AnalyticsDateRange] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
