# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.unchecked_base_model import UncheckedBaseModel
from .list_agent_templates_agent_templates_response_data_item_single_prompt_config_tools_item_type import (
    ListAgentTemplatesAgentTemplatesResponseDataItemSinglePromptConfigToolsItemType,
)


class ListAgentTemplatesAgentTemplatesResponseDataItemSinglePromptConfigToolsItem(UncheckedBaseModel):
    type: typing.Optional[ListAgentTemplatesAgentTemplatesResponseDataItemSinglePromptConfigToolsItemType] = (
        pydantic.Field(default=None)
    )
    """
    The tool type — drives runtime dispatch.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the tool
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    What the tool does
    """

    input_schema: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    JSON Schema describing the tool's input parameters
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
