# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.unchecked_base_model import UncheckedBaseModel
from .archive_agent_agents_response_data import ArchiveAgentAgentsResponseData


class ArchiveAgentAgentsResponse(UncheckedBaseModel):
    status: typing.Optional[bool] = None
    data: typing.Optional[ArchiveAgentAgentsResponseData] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
