# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_call_action_request_action_type import CreateCallActionRequestActionType
    from .create_call_action_request_category import CreateCallActionRequestCategory
    from .create_call_action_request_config import CreateCallActionRequestConfig
    from .create_call_action_response import CreateCallActionResponse
    from .delete_call_action_response import DeleteCallActionResponse
    from .delete_call_action_response_data import DeleteCallActionResponseData
    from .get_call_action_response import GetCallActionResponse
    from .list_call_actions_request_category import ListCallActionsRequestCategory
    from .list_call_actions_response import ListCallActionsResponse
    from .list_call_actions_response_data import ListCallActionsResponseData
    from .update_call_action_request_action_type import UpdateCallActionRequestActionType
    from .update_call_action_request_category import UpdateCallActionRequestCategory
    from .update_call_action_request_config import UpdateCallActionRequestConfig
    from .update_call_action_response import UpdateCallActionResponse
_dynamic_imports: typing.Dict[str, str] = {
    "CreateCallActionRequestActionType": ".create_call_action_request_action_type",
    "CreateCallActionRequestCategory": ".create_call_action_request_category",
    "CreateCallActionRequestConfig": ".create_call_action_request_config",
    "CreateCallActionResponse": ".create_call_action_response",
    "DeleteCallActionResponse": ".delete_call_action_response",
    "DeleteCallActionResponseData": ".delete_call_action_response_data",
    "GetCallActionResponse": ".get_call_action_response",
    "ListCallActionsRequestCategory": ".list_call_actions_request_category",
    "ListCallActionsResponse": ".list_call_actions_response",
    "ListCallActionsResponseData": ".list_call_actions_response_data",
    "UpdateCallActionRequestActionType": ".update_call_action_request_action_type",
    "UpdateCallActionRequestCategory": ".update_call_action_request_category",
    "UpdateCallActionRequestConfig": ".update_call_action_request_config",
    "UpdateCallActionResponse": ".update_call_action_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateCallActionRequestActionType",
    "CreateCallActionRequestCategory",
    "CreateCallActionRequestConfig",
    "CreateCallActionResponse",
    "DeleteCallActionResponse",
    "DeleteCallActionResponseData",
    "GetCallActionResponse",
    "ListCallActionsRequestCategory",
    "ListCallActionsResponse",
    "ListCallActionsResponseData",
    "UpdateCallActionRequestActionType",
    "UpdateCallActionRequestCategory",
    "UpdateCallActionRequestConfig",
    "UpdateCallActionResponse",
]
