# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.serialization import FieldMetadata
from ....core.unchecked_base_model import UncheckedBaseModel


class GetCallsResponseDataToolCallsItem(UncheckedBaseModel):
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Tool name as configured on the agent
    """

    tool_call_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="toolCallId"), pydantic.Field(alias="toolCallId")
    ] = None
    timestamp: typing.Optional[dt.datetime] = None
    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Tool kind, e.g. `api_call`, `client_tool`, `knowledge_base_search`. Null on older calls.
    """

    method: typing.Optional[str] = pydantic.Field(default=None)
    """
    HTTP method for `api_call` tools
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Template URL for `api_call` tools, with `{{param}}` placeholders unresolved
    """

    execution_ms: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="executionMs"),
        pydantic.Field(alias="executionMs", description="Time the tool took to run, in milliseconds"),
    ] = None
    context_tokens: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="contextTokens"),
        pydantic.Field(
            alias="contextTokens",
            description="Tokens this tool exchange added to the context. Set only when the tool ran alone in its LLM-call window; otherwise see `groupContextTokens`.",
        ),
    ] = None
    group_context_tokens: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="groupContextTokens"),
        pydantic.Field(
            alias="groupContextTokens",
            description="Combined token cost of every tool that shared this LLM-call window. The provider bills the window as one number, so no per-tool split exists.",
        ),
    ] = None
    token_group_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="tokenGroupId"),
        pydantic.Field(
            alias="tokenGroupId",
            description="Shared by every tool in the same LLM-call window. Null when the tool ran alone.",
        ),
    ] = None
    arguments: typing.Optional[typing.Any] = pydantic.Field(default=None)
    """
    Arguments the agent passed to the tool
    """

    response: typing.Optional[typing.Any] = pydantic.Field(default=None)
    """
    What the tool returned
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
