# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.serialization import FieldMetadata
from ....core.unchecked_base_model import UncheckedBaseModel
from .list_calls_response_data_logs_item_post_call_analytics_disposition_metrics_item import (
    ListCallsResponseDataLogsItemPostCallAnalyticsDispositionMetricsItem,
)


class ListCallsResponseDataLogsItemPostCallAnalytics(UncheckedBaseModel):
    """
    Post-call analytics results evaluated against the call transcript.
    Contains disposition metric values with confidence scores.
    """

    summary: typing.Optional[str] = pydantic.Field(default=None)
    """
    Auto-generated summary of the call
    """

    disposition_metrics: typing_extensions.Annotated[
        typing.Optional[typing.List[ListCallsResponseDataLogsItemPostCallAnalyticsDispositionMetricsItem]],
        FieldMetadata(alias="dispositionMetrics"),
        pydantic.Field(alias="dispositionMetrics", description="Evaluated disposition metrics for this call"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
