# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.serialization import FieldMetadata
from ....core.unchecked_base_model import UncheckedBaseModel
from .search_calls_response_data_logs_item_turn_latency_metrics_transitions_item import (
    SearchCallsResponseDataLogsItemTurnLatencyMetricsTransitionsItem,
)


class SearchCallsResponseDataLogsItemTurnLatencyMetrics(UncheckedBaseModel):
    """
    Per-turn latency statistics for the call
    """

    avg_latency: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="avgLatency"), pydantic.Field(alias="avgLatency")
    ] = None
    median_latency: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="medianLatency"), pydantic.Field(alias="medianLatency")
    ] = None
    min_latency: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="minLatency"), pydantic.Field(alias="minLatency")
    ] = None
    max_latency: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="maxLatency"), pydantic.Field(alias="maxLatency")
    ] = None
    turns: typing.Optional[float] = None
    latencies: typing.Optional[typing.List[float]] = None
    transitions: typing.Optional[typing.List[SearchCallsResponseDataLogsItemTurnLatencyMetricsTransitionsItem]] = None
    processed_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="processedAt"), pydantic.Field(alias="processedAt")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
