# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        CreateKnowledgeBaseResponse,
        DeleteKnowledgeBaseResponse,
        DeleteKnowledgebaseKnowledgeBaseIdItemsKnowledgeBaseItemIdResponse,
        DeleteKnowledgebaseKnowledgeBaseIdScrapedUrlsKnowledgeBaseScrapedUrlsIdResponse,
        ExtractSitemapUrlsKnowledgeBaseResponse,
        ExtractSitemapUrlsKnowledgeBaseResponseData,
        GetKnowledgeBaseResponse,
        GetKnowledgebaseIdItemsResponse,
        GetKnowledgebaseIdScrapedUrlsResponse,
        GetKnowledgebaseIdScrapedUrlsResponseDataItem,
        ListKnowledgeBaseResponse,
        PostKnowledgebaseCompeleteFileUploadResponse,
        PostKnowledgebaseGetPresignedUrlResponse,
        PostKnowledgebaseGetPresignedUrlResponseData,
        PostKnowledgebaseIdItemsUploadMediaResponse,
        PostKnowledgebaseIdResponse,
        ScrapeUrlsKnowledgeBaseResponse,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "CreateKnowledgeBaseResponse": ".types",
    "DeleteKnowledgeBaseResponse": ".types",
    "DeleteKnowledgebaseKnowledgeBaseIdItemsKnowledgeBaseItemIdResponse": ".types",
    "DeleteKnowledgebaseKnowledgeBaseIdScrapedUrlsKnowledgeBaseScrapedUrlsIdResponse": ".types",
    "ExtractSitemapUrlsKnowledgeBaseResponse": ".types",
    "ExtractSitemapUrlsKnowledgeBaseResponseData": ".types",
    "GetKnowledgeBaseResponse": ".types",
    "GetKnowledgebaseIdItemsResponse": ".types",
    "GetKnowledgebaseIdScrapedUrlsResponse": ".types",
    "GetKnowledgebaseIdScrapedUrlsResponseDataItem": ".types",
    "ListKnowledgeBaseResponse": ".types",
    "PostKnowledgebaseCompeleteFileUploadResponse": ".types",
    "PostKnowledgebaseGetPresignedUrlResponse": ".types",
    "PostKnowledgebaseGetPresignedUrlResponseData": ".types",
    "PostKnowledgebaseIdItemsUploadMediaResponse": ".types",
    "PostKnowledgebaseIdResponse": ".types",
    "ScrapeUrlsKnowledgeBaseResponse": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateKnowledgeBaseResponse",
    "DeleteKnowledgeBaseResponse",
    "DeleteKnowledgebaseKnowledgeBaseIdItemsKnowledgeBaseItemIdResponse",
    "DeleteKnowledgebaseKnowledgeBaseIdScrapedUrlsKnowledgeBaseScrapedUrlsIdResponse",
    "ExtractSitemapUrlsKnowledgeBaseResponse",
    "ExtractSitemapUrlsKnowledgeBaseResponseData",
    "GetKnowledgeBaseResponse",
    "GetKnowledgebaseIdItemsResponse",
    "GetKnowledgebaseIdScrapedUrlsResponse",
    "GetKnowledgebaseIdScrapedUrlsResponseDataItem",
    "ListKnowledgeBaseResponse",
    "PostKnowledgebaseCompeleteFileUploadResponse",
    "PostKnowledgebaseGetPresignedUrlResponse",
    "PostKnowledgebaseGetPresignedUrlResponseData",
    "PostKnowledgebaseIdItemsUploadMediaResponse",
    "PostKnowledgebaseIdResponse",
    "ScrapeUrlsKnowledgeBaseResponse",
]
