# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel
from .billing_ledger_entry_transaction_type import BillingLedgerEntryTransactionType


class BillingLedgerEntry(UncheckedBaseModel):
    id: str = pydantic.Field()
    """
    Ledger row identifier.
    """

    transaction_type: typing_extensions.Annotated[
        BillingLedgerEntryTransactionType,
        FieldMetadata(alias="transactionType"),
        pydantic.Field(alias="transactionType"),
    ]
    amount: float = pydantic.Field()
    """
    Signed credit delta in USD. Positive for additions (`CREDIT_PURCHASE`, `AUTO_RELOAD`, `COUPON_CREDIT`, `SIGNUP_BONUS`), negative for spend (`USAGE_DEDUCTION`).
    """

    balance_after: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="balanceAfter"),
        pydantic.Field(alias="balanceAfter", description="Balance after this row was applied."),
    ]
    feature_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="featureId"),
        pydantic.Field(
            alias="featureId",
            description="Product feature that triggered the row (e.g. `tts.generate`, `waves.stt`). Only set on `USAGE_DEDUCTION`.",
        ),
    ] = None
    reference_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="referenceId"),
        pydantic.Field(
            alias="referenceId", description="External reference tying this row to a purchase, coupon, or admin action."
        ),
    ] = None
    description: typing.Optional[str] = None
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    call_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="callId"),
        pydantic.Field(alias="callId", description="Associated call ID, when the row was produced by a call."),
    ] = None
    agent_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="agentId"), pydantic.Field(alias="agentId")
    ] = None
    request_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="requestId"), pydantic.Field(alias="requestId")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
