# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .call_action_condition_operator import CallActionConditionOperator


class CallActionCondition(UncheckedBaseModel):
    """
    A filter condition evaluated against provider record fields
    """

    field: str = pydantic.Field()
    """
    Provider record field name
    """

    operator: CallActionConditionOperator = pydantic.Field()
    """
    Comparison operator
    """

    value: str = pydantic.Field()
    """
    Value to compare against
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
