# This file was auto-generated by Fern from our API Definition.

import typing

CallActionConditionOperator = typing.Union[
    typing.Literal[
        "eq", "neq", "gt", "gte", "lt", "lte", "in", "nin", "contains", "notContains", "startsWith", "endsWith"
    ],
    typing.Any,
]
