# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from .webhook_event_envelope import WebhookEventEnvelope
from .webhook_event_post_conversation_metadata import WebhookEventPostConversationMetadata


class WebhookEventPostConversation(WebhookEventEnvelope):
    """
    Fired **after** the call ends. Contains the full transcript, call
    metadata, recording URL, and all agent variables that were in scope
    during the conversation.
    """

    metadata: WebhookEventPostConversationMetadata

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
