# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ...core.api_error import ApiError
from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.http_response import AsyncHttpResponse, HttpResponse
from ...core.parse_error import ParsingError
from ...core.request_options import RequestOptions
from ...core.serialization import convert_and_respect_annotation_metadata
from ...core.unchecked_base_model import construct_type
from ..errors.bad_request_error import BadRequestError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.disposition_metric import DispositionMetric
from ..types.pca_response import PcaResponse
from .types.generate_post_call_analysis_response import GeneratePostCallAnalysisResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawPostCallAnalysisClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def analyze(
        self,
        *,
        transcript: str,
        disposition_metrics: typing.Optional[typing.Sequence[DispositionMetric]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PcaResponse]:
        """
        Analyze a call transcript and extract structured disposition metrics. Provide the
        transcript and the metrics you want extracted; the response returns a short summary
        plus one result per requested metric, each with a value, a confidence score, and the
        transcript evidence for it. Values are grounded strictly in the transcript (no
        inference); when evidence is absent, the type's fallback is used.

        Parameters
        ----------
        transcript : str
            The full call transcript to analyze. Max 60,000 characters (~15,000 tokens / ~1 hour call).

        disposition_metrics : typing.Optional[typing.Sequence[DispositionMetric]]
            The metrics to extract. Omit or pass an empty array to get just a summary.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PcaResponse]
            Analysis complete.
        """
        _response = self._client_wrapper.httpx_client.request(
            "waves/v1/pca",
            base_url=self._client_wrapper.get_environment().waves,
            method="POST",
            json={
                "transcript": transcript,
                "dispositionMetrics": convert_and_respect_annotation_metadata(
                    object_=disposition_metrics, annotation=typing.Sequence[DispositionMetric], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PcaResponse,
                    construct_type(
                        type_=PcaResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def generate(
        self, *, prompt: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GeneratePostCallAnalysisResponse]:
        """
        Run a single-prompt generation and get the model's text output. A lightweight
        text-in / text-out endpoint (no chat history); for multi-turn chat use the
        Electron chat completions API instead.

        Parameters
        ----------
        prompt : str
            The prompt to generate from. Max 60,000 characters.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GeneratePostCallAnalysisResponse]
            Generation complete.
        """
        _response = self._client_wrapper.httpx_client.request(
            "waves/v1/pca/generate",
            base_url=self._client_wrapper.get_environment().waves,
            method="POST",
            json={
                "prompt": prompt,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GeneratePostCallAnalysisResponse,
                    construct_type(
                        type_=GeneratePostCallAnalysisResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawPostCallAnalysisClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def analyze(
        self,
        *,
        transcript: str,
        disposition_metrics: typing.Optional[typing.Sequence[DispositionMetric]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PcaResponse]:
        """
        Analyze a call transcript and extract structured disposition metrics. Provide the
        transcript and the metrics you want extracted; the response returns a short summary
        plus one result per requested metric, each with a value, a confidence score, and the
        transcript evidence for it. Values are grounded strictly in the transcript (no
        inference); when evidence is absent, the type's fallback is used.

        Parameters
        ----------
        transcript : str
            The full call transcript to analyze. Max 60,000 characters (~15,000 tokens / ~1 hour call).

        disposition_metrics : typing.Optional[typing.Sequence[DispositionMetric]]
            The metrics to extract. Omit or pass an empty array to get just a summary.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PcaResponse]
            Analysis complete.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "waves/v1/pca",
            base_url=self._client_wrapper.get_environment().waves,
            method="POST",
            json={
                "transcript": transcript,
                "dispositionMetrics": convert_and_respect_annotation_metadata(
                    object_=disposition_metrics, annotation=typing.Sequence[DispositionMetric], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PcaResponse,
                    construct_type(
                        type_=PcaResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def generate(
        self, *, prompt: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GeneratePostCallAnalysisResponse]:
        """
        Run a single-prompt generation and get the model's text output. A lightweight
        text-in / text-out endpoint (no chat history); for multi-turn chat use the
        Electron chat completions API instead.

        Parameters
        ----------
        prompt : str
            The prompt to generate from. Max 60,000 characters.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GeneratePostCallAnalysisResponse]
            Generation complete.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "waves/v1/pca/generate",
            base_url=self._client_wrapper.get_environment().waves,
            method="POST",
            json={
                "prompt": prompt,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GeneratePostCallAnalysisResponse,
                    construct_type(
                        type_=GeneratePostCallAnalysisResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
