# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawAgentTelephonyClient, RawAgentTelephonyClient
from .types.attach_answer_agent_telephony_request_source_kind import AttachAnswerAgentTelephonyRequestSourceKind
from .types.attach_answer_agent_telephony_response import AttachAnswerAgentTelephonyResponse
from .types.attach_caller_id_agent_telephony_request_source_kind import AttachCallerIdAgentTelephonyRequestSourceKind
from .types.attach_caller_id_agent_telephony_response import AttachCallerIdAgentTelephonyResponse
from .types.detach_answer_agent_telephony_response import DetachAnswerAgentTelephonyResponse
from .types.detach_caller_id_agent_telephony_response import DetachCallerIdAgentTelephonyResponse
from .types.list_answers_agent_telephony_response import ListAnswersAgentTelephonyResponse
from .types.list_caller_ids_agent_telephony_response import ListCallerIdsAgentTelephonyResponse
from .types.set_transfer_source_agent_telephony_response import SetTransferSourceAgentTelephonyResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AgentTelephonyClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgentTelephonyClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAgentTelephonyClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgentTelephonyClient
        """
        return self._raw_client

    def list_answers(
        self, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListAnswersAgentTelephonyResponse:
        """
        Lists the inbound sources (rented numbers and inbound SIP trunks) this agent
        answers. Each entry is `{ bindingId, sourceKind, sourceId, label }` where `label`
        is the phone number or the trunk's name.

        Parameters
        ----------
        agent_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAnswersAgentTelephonyResponse
            The agent's answering sources

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.agent_telephony.list_answers(
            agent_id="agentId",
        )
        """
        _response = self._raw_client.list_answers(agent_id, request_options=request_options)
        return _response.data

    def attach_answer(
        self,
        agent_id: str,
        *,
        source_kind: AttachAnswerAgentTelephonyRequestSourceKind,
        source_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AttachAnswerAgentTelephonyResponse:
        """
        Makes the agent answer calls arriving on a rented number or inbound SIP trunk you
        own. Requires an admin-role key. A source is answered by exactly one agent: if
        another agent already answers it, `409` identifies that agent by id
        ("Already answered by another agent (...). Detach it there first."). This replaces the legacy
        `telephonyProductId` field on agent writes.

        Parameters
        ----------
        agent_id : str

        source_kind : AttachAnswerAgentTelephonyRequestSourceKind

        source_id : str
            The phone number product ID, or the inbound SIP trunk ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AttachAnswerAgentTelephonyResponse
            Binding created. Returns the stored binding record (not the read shape `GET .../answers` uses).

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.agent_telephony.attach_answer(
            agent_id="agentId",
            source_kind="phoneNumber",
            source_id="60d0fe4f5311236168a109ca",
        )
        """
        _response = self._raw_client.attach_answer(
            agent_id, source_kind=source_kind, source_id=source_id, request_options=request_options
        )
        return _response.data

    def detach_answer(
        self, agent_id: str, source_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DetachAnswerAgentTelephonyResponse:
        """
        Stops the agent answering on the source. `sourceId` is the phone number product ID
        or inbound trunk ID (not the binding ID). Requires an admin-role key.

        Parameters
        ----------
        agent_id : str

        source_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DetachAnswerAgentTelephonyResponse
            Source detached

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.agent_telephony.detach_answer(
            agent_id="agentId",
            source_id="sourceId",
        )
        """
        _response = self._raw_client.detach_answer(agent_id, source_id, request_options=request_options)
        return _response.data

    def list_caller_ids(
        self, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListCallerIdsAgentTelephonyResponse:
        """
        **Deprecated.** The per-agent caller-ID surface is the backward-compatibility
        bridge for integrations that never sent a from-number; it sunsets with the
        migration window, after which `fromNumber` is required on outbound calls.
        Responses carry a `Deprecation: true` header.

        Lists the caller IDs this agent may dial from when an outbound call does not pass
        `fromNumber`. Returned in the order they were attached; a call without a
        `fromNumber` uses the first entry that still resolves (inactive numbers and
        numbers a trunk no longer presents are skipped at dial time but still listed here).

        Parameters
        ----------
        agent_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCallerIdsAgentTelephonyResponse
            The agent's default caller IDs, in attach order

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.agent_telephony.list_caller_ids(
            agent_id="agentId",
        )
        """
        _response = self._raw_client.list_caller_ids(agent_id, request_options=request_options)
        return _response.data

    def attach_caller_id(
        self,
        agent_id: str,
        *,
        source_kind: AttachCallerIdAgentTelephonyRequestSourceKind,
        source_id: str,
        number: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AttachCallerIdAgentTelephonyResponse:
        """
        **Deprecated.** Part of the compatibility bridge; sunsets with the migration
        window. New integrations should pass `fromNumber` on each call instead.
        Responses carry a `Deprecation: true` header.

        Lets the agent dial from a rented number or an outbound SIP trunk's number when a
        call does not pass `fromNumber`. Requires an admin-role key. Unlike answering
        sources, caller IDs are **shared**: many agents may present the same number, so
        attaching never conflicts.

        A caller ID names the exact number it dials from. A trunk presents many numbers, so
        a `sipTrunk` attach must carry `number` (one of that trunk's numbers); a
        `phoneNumber` source is its own number, so it must not.

        Parameters
        ----------
        agent_id : str

        source_kind : AttachCallerIdAgentTelephonyRequestSourceKind

        source_id : str
            The phone number product ID, or the outbound SIP trunk ID.

        number : typing.Optional[str]
            Required for `sipTrunk` sources: which of the trunk's numbers this agent
            dials from (E.164 with leading `+`). Must be omitted for `phoneNumber`
            sources.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AttachCallerIdAgentTelephonyResponse
            Caller ID attached

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.agent_telephony.attach_caller_id(
            agent_id="agentId",
            source_kind="phoneNumber",
            source_id="sourceId",
        )
        """
        _response = self._raw_client.attach_caller_id(
            agent_id, source_kind=source_kind, source_id=source_id, number=number, request_options=request_options
        )
        return _response.data

    def detach_caller_id(
        self, agent_id: str, source_id: str, *, number: str, request_options: typing.Optional[RequestOptions] = None
    ) -> DetachCallerIdAgentTelephonyResponse:
        """
        Removes the source from the agent's caller-ID list. `sourceId` is the phone number
        product ID or outbound trunk ID. Requires an admin-role key.

        `number` is required for every source kind: it names the caller ID to detach.
        Omitting it is refused with `400` ("Say which caller ID to detach: pass
        ?number=+E164 (URL-encode the +)"). For a `phoneNumber` source, pass the
        number itself.

        Parameters
        ----------
        agent_id : str

        source_id : str

        number : str
            The E.164 number of the caller ID to detach. URL-encode the `+` as `%2B`
            (e.g. `?number=%2B14155552671`). For a `phoneNumber` source, pass the
            number itself.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DetachCallerIdAgentTelephonyResponse
            Source detached

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.agent_telephony.detach_caller_id(
            agent_id="agentId",
            source_id="sourceId",
            number="number",
        )
        """
        _response = self._raw_client.detach_caller_id(
            agent_id, source_id, number=number, request_options=request_options
        )
        return _response.data

    def set_transfer_source(
        self,
        agent_id: str,
        *,
        transfer_from_number: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SetTransferSourceAgentTelephonyResponse:
        """
        Sets the number the agent's call transfers dial out from. Must be a number your
        organization owns (rented, or a caller ID on an outbound trunk); `null` clears it.
        When unset, transfers on outbound calls fall back to the call's own caller ID, and
        transfers on inbound calls are refused. Not part of versioned agent config:
        changing it never requires an agent release.

        Parameters
        ----------
        agent_id : str

        transfer_from_number : typing.Optional[str]
            E.164 with leading `+`, or `null` to clear.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SetTransferSourceAgentTelephonyResponse
            Transfer caller ID set

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.agent_telephony.set_transfer_source(
            agent_id="agentId",
        )
        """
        _response = self._raw_client.set_transfer_source(
            agent_id, transfer_from_number=transfer_from_number, request_options=request_options
        )
        return _response.data


class AsyncAgentTelephonyClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgentTelephonyClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAgentTelephonyClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgentTelephonyClient
        """
        return self._raw_client

    async def list_answers(
        self, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListAnswersAgentTelephonyResponse:
        """
        Lists the inbound sources (rented numbers and inbound SIP trunks) this agent
        answers. Each entry is `{ bindingId, sourceKind, sourceId, label }` where `label`
        is the phone number or the trunk's name.

        Parameters
        ----------
        agent_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAnswersAgentTelephonyResponse
            The agent's answering sources

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.agent_telephony.list_answers(
                agent_id="agentId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_answers(agent_id, request_options=request_options)
        return _response.data

    async def attach_answer(
        self,
        agent_id: str,
        *,
        source_kind: AttachAnswerAgentTelephonyRequestSourceKind,
        source_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AttachAnswerAgentTelephonyResponse:
        """
        Makes the agent answer calls arriving on a rented number or inbound SIP trunk you
        own. Requires an admin-role key. A source is answered by exactly one agent: if
        another agent already answers it, `409` identifies that agent by id
        ("Already answered by another agent (...). Detach it there first."). This replaces the legacy
        `telephonyProductId` field on agent writes.

        Parameters
        ----------
        agent_id : str

        source_kind : AttachAnswerAgentTelephonyRequestSourceKind

        source_id : str
            The phone number product ID, or the inbound SIP trunk ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AttachAnswerAgentTelephonyResponse
            Binding created. Returns the stored binding record (not the read shape `GET .../answers` uses).

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.agent_telephony.attach_answer(
                agent_id="agentId",
                source_kind="phoneNumber",
                source_id="60d0fe4f5311236168a109ca",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.attach_answer(
            agent_id, source_kind=source_kind, source_id=source_id, request_options=request_options
        )
        return _response.data

    async def detach_answer(
        self, agent_id: str, source_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DetachAnswerAgentTelephonyResponse:
        """
        Stops the agent answering on the source. `sourceId` is the phone number product ID
        or inbound trunk ID (not the binding ID). Requires an admin-role key.

        Parameters
        ----------
        agent_id : str

        source_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DetachAnswerAgentTelephonyResponse
            Source detached

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.agent_telephony.detach_answer(
                agent_id="agentId",
                source_id="sourceId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.detach_answer(agent_id, source_id, request_options=request_options)
        return _response.data

    async def list_caller_ids(
        self, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListCallerIdsAgentTelephonyResponse:
        """
        **Deprecated.** The per-agent caller-ID surface is the backward-compatibility
        bridge for integrations that never sent a from-number; it sunsets with the
        migration window, after which `fromNumber` is required on outbound calls.
        Responses carry a `Deprecation: true` header.

        Lists the caller IDs this agent may dial from when an outbound call does not pass
        `fromNumber`. Returned in the order they were attached; a call without a
        `fromNumber` uses the first entry that still resolves (inactive numbers and
        numbers a trunk no longer presents are skipped at dial time but still listed here).

        Parameters
        ----------
        agent_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCallerIdsAgentTelephonyResponse
            The agent's default caller IDs, in attach order

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.agent_telephony.list_caller_ids(
                agent_id="agentId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_caller_ids(agent_id, request_options=request_options)
        return _response.data

    async def attach_caller_id(
        self,
        agent_id: str,
        *,
        source_kind: AttachCallerIdAgentTelephonyRequestSourceKind,
        source_id: str,
        number: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AttachCallerIdAgentTelephonyResponse:
        """
        **Deprecated.** Part of the compatibility bridge; sunsets with the migration
        window. New integrations should pass `fromNumber` on each call instead.
        Responses carry a `Deprecation: true` header.

        Lets the agent dial from a rented number or an outbound SIP trunk's number when a
        call does not pass `fromNumber`. Requires an admin-role key. Unlike answering
        sources, caller IDs are **shared**: many agents may present the same number, so
        attaching never conflicts.

        A caller ID names the exact number it dials from. A trunk presents many numbers, so
        a `sipTrunk` attach must carry `number` (one of that trunk's numbers); a
        `phoneNumber` source is its own number, so it must not.

        Parameters
        ----------
        agent_id : str

        source_kind : AttachCallerIdAgentTelephonyRequestSourceKind

        source_id : str
            The phone number product ID, or the outbound SIP trunk ID.

        number : typing.Optional[str]
            Required for `sipTrunk` sources: which of the trunk's numbers this agent
            dials from (E.164 with leading `+`). Must be omitted for `phoneNumber`
            sources.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AttachCallerIdAgentTelephonyResponse
            Caller ID attached

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.agent_telephony.attach_caller_id(
                agent_id="agentId",
                source_kind="phoneNumber",
                source_id="sourceId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.attach_caller_id(
            agent_id, source_kind=source_kind, source_id=source_id, number=number, request_options=request_options
        )
        return _response.data

    async def detach_caller_id(
        self, agent_id: str, source_id: str, *, number: str, request_options: typing.Optional[RequestOptions] = None
    ) -> DetachCallerIdAgentTelephonyResponse:
        """
        Removes the source from the agent's caller-ID list. `sourceId` is the phone number
        product ID or outbound trunk ID. Requires an admin-role key.

        `number` is required for every source kind: it names the caller ID to detach.
        Omitting it is refused with `400` ("Say which caller ID to detach: pass
        ?number=+E164 (URL-encode the +)"). For a `phoneNumber` source, pass the
        number itself.

        Parameters
        ----------
        agent_id : str

        source_id : str

        number : str
            The E.164 number of the caller ID to detach. URL-encode the `+` as `%2B`
            (e.g. `?number=%2B14155552671`). For a `phoneNumber` source, pass the
            number itself.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DetachCallerIdAgentTelephonyResponse
            Source detached

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.agent_telephony.detach_caller_id(
                agent_id="agentId",
                source_id="sourceId",
                number="number",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.detach_caller_id(
            agent_id, source_id, number=number, request_options=request_options
        )
        return _response.data

    async def set_transfer_source(
        self,
        agent_id: str,
        *,
        transfer_from_number: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SetTransferSourceAgentTelephonyResponse:
        """
        Sets the number the agent's call transfers dial out from. Must be a number your
        organization owns (rented, or a caller ID on an outbound trunk); `null` clears it.
        When unset, transfers on outbound calls fall back to the call's own caller ID, and
        transfers on inbound calls are refused. Not part of versioned agent config:
        changing it never requires an agent release.

        Parameters
        ----------
        agent_id : str

        transfer_from_number : typing.Optional[str]
            E.164 with leading `+`, or `null` to clear.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SetTransferSourceAgentTelephonyResponse
            Transfer caller ID set

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.agent_telephony.set_transfer_source(
                agent_id="agentId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.set_transfer_source(
            agent_id, transfer_from_number=transfer_from_number, request_options=request_options
        )
        return _response.data
