# This file was auto-generated by Fern from our API Definition.

import typing

ResponseDoneResponseStatus = typing.Union[typing.Literal["completed", "cancelled", "incomplete", "failed"], typing.Any]
