# This file was auto-generated by Fern from our API Definition.

import typing

ListAgentTemplatesAgentTemplatesResponseDataItemCallType = typing.Union[
    typing.Literal["Inbound", "Outbound", "Both"], typing.Any
]
