# This file was auto-generated by Fern from our API Definition.

import typing

from ... import core
from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawAudienceClient, RawAudienceClient
from .types.delete_audience_id_members_response import DeleteAudienceIdMembersResponse
from .types.delete_audience_id_response import DeleteAudienceIdResponse
from .types.get_audience_id_members_response import GetAudienceIdMembersResponse
from .types.get_audience_id_members_search_response import GetAudienceIdMembersSearchResponse
from .types.get_audience_response import GetAudienceResponse
from .types.list_audience_response import ListAudienceResponse
from .types.post_audience_id_members_response import PostAudienceIdMembersResponse
from .types.post_audience_response import PostAudienceResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AudienceClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAudienceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAudienceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAudienceClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListAudienceResponse:
        """
        Retrieve all audiences created by the authenticated user. Users can only access audiences they have created.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAudienceResponse
            Successfully retrieved audiences

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.audience.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def create_audience_with_csv_upload(
        self,
        *,
        name: str,
        phone_number_column_name: str,
        file: core.File,
        description: typing.Optional[str] = OMIT,
        identifier_column_name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostAudienceResponse:
        """
        Create a new audience by uploading a CSV file containing phone numbers.
        Only CSV text files are accepted — binary files will produce malformed data.

        **Additional 400 cases:**
        - Duplicate phone numbers in the CSV: `"Some phone numbers in your CSV already exist in this audience. Please remove duplicate entries and try again."`
        - Member limit exceeded: `"Audience cannot exceed X members"`

        Parameters
        ----------
        name : str
            The name of the audience

        phone_number_column_name : str
            The name of the column in the CSV that contains phone numbers

        file : core.File
            See core.File for more documentation

        description : typing.Optional[str]
            Optional description of the audience

        identifier_column_name : typing.Optional[str]
            The name of the column in the CSV that contains identifiers (e.g., names)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostAudienceResponse
            Audience created successfully

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.audience.create_audience_with_csv_upload(
            name="name",
            phone_number_column_name="phoneNumberColumnName",
        )
        """
        _response = self._raw_client.create_audience_with_csv_upload(
            name=name,
            phone_number_column_name=phone_number_column_name,
            file=file,
            description=description,
            identifier_column_name=identifier_column_name,
            request_options=request_options,
        )
        return _response.data

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetAudienceResponse:
        """
        Retrieve a specific audience by its ID.
        Note: if the audience belongs to a different organization, the API returns 404 (not 403) — ownership is deliberately obscured.

        Parameters
        ----------
        id : str
            The unique identifier of the audience

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAudienceResponse
            Successfully retrieved audience

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.audience.get(
            id="60d0fe4f5311236168a109ca",
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data

    def delete_audience(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteAudienceIdResponse:
        """
        Delete a specific audience by its ID. Users can only delete audiences they created.

        **400 is returned if the audience is used by an active campaign:**
        `"can't delete audience, campaign with this audience <id> exists"`
        Remove the campaign first, then retry deletion.

        On success, `data` is always an empty array `[]`.

        Parameters
        ----------
        id : str
            The unique identifier of the audience to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteAudienceIdResponse
            Audience deleted successfully

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.audience.delete_audience(
            id="60d0fe4f5311236168a109ca",
        )
        """
        _response = self._raw_client.delete_audience(id, request_options=request_options)
        return _response.data

    def get_audience_members(
        self,
        id: str,
        *,
        page: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetAudienceIdMembersResponse:
        """
        Retrieve members of a specific audience with pagination support. Users can only access members of audiences they created.

        Parameters
        ----------
        id : str
            The unique identifier of the audience

        page : typing.Optional[int]
            Page number for pagination (default is 1)

        offset : typing.Optional[int]
            Number of items per page (default is 5).
            Note: this parameter is named "offset", not "limit" — sending ?limit=N is silently ignored.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAudienceIdMembersResponse
            Successfully retrieved audience members

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.audience.get_audience_members(
            id="60d0fe4f5311236168a109ca",
            page=1,
            offset=10,
        )
        """
        _response = self._raw_client.get_audience_members(id, page=page, offset=offset, request_options=request_options)
        return _response.data

    def add_audience_members(
        self,
        id: str,
        *,
        members: typing.Sequence[typing.Dict[str, typing.Any]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostAudienceIdMembersResponse:
        """
        Add new members to an existing audience.

        Each member object must include a key matching the audience's `phoneNumberColumnName`.
        If it's missing, the API returns 400: `"Each member must have a <phoneNumberColumnName> field"`.
        Adding members that would exceed the audience limit also returns 400.

        Note: if the audience belongs to a different organization, the API returns 404 (not 403).

        Parameters
        ----------
        id : str
            The unique identifier of the audience

        members : typing.Sequence[typing.Dict[str, typing.Any]]
            Array of member objects with dynamic structure based on audience configuration

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostAudienceIdMembersResponse
            Members added successfully

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.audience.add_audience_members(
            id="60d0fe4f5311236168a109ca",
            members=[
                {
                    "phoneNumber": "+1234567890",
                    "name": "John Doe",
                    "email": "john@example.com",
                }
            ],
        )
        """
        _response = self._raw_client.add_audience_members(id, members=members, request_options=request_options)
        return _response.data

    def delete_audience_members(
        self, id: str, *, member_ids: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteAudienceIdMembersResponse:
        """
        Remove specific members from an audience by their member IDs. Users can only delete members from audiences they created.

        Parameters
        ----------
        id : str
            The unique identifier of the audience

        member_ids : typing.Sequence[str]
            Array of member IDs to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteAudienceIdMembersResponse
            Members deleted successfully

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.audience.delete_audience_members(
            id="60d0fe4f5311236168a109ca",
            member_ids=["60d0fe4f5311236168a109cd"],
        )
        """
        _response = self._raw_client.delete_audience_members(id, member_ids=member_ids, request_options=request_options)
        return _response.data

    def search_audience_members(
        self, id: str, *, query: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> GetAudienceIdMembersSearchResponse:
        """
        Search for members within a specific audience using flexible search parameters. Users can only search members of audiences they created.

        **Search Types:**
        - **General Search** (`query`): Searches across all fields in the audience member data
        - **Field-Specific Search**: Use any field name as a parameter (e.g., `firstName=john`, `phoneNumber=123456`, `email=test@example.com`)

        **Examples:**
        - `?query=john` - General search across all fields
        - `?firstName=john` - Search specifically in firstName field
        - `?phoneNumber=555-1234` - Search specifically in phoneNumber field
        - `?firstName=john&lastName=doe` - Search for members matching both criteria

        **Note:** When using phoneNumber field, do not use quotes around the phone number. You can use either a general search OR field-specific searches, but not both simultaneously.

        Parameters
        ----------
        id : str
            The unique identifier of the audience

        query : typing.Optional[str]
            General search term that searches across all fields in audience member data

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAudienceIdMembersSearchResponse
            Search results returned successfully

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.audience.search_audience_members(
            id="60d0fe4f5311236168a109ca",
            query="john",
        )
        """
        _response = self._raw_client.search_audience_members(id, query=query, request_options=request_options)
        return _response.data


class AsyncAudienceClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAudienceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAudienceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAudienceClient
        """
        return self._raw_client

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListAudienceResponse:
        """
        Retrieve all audiences created by the authenticated user. Users can only access audiences they have created.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAudienceResponse
            Successfully retrieved audiences

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.audience.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def create_audience_with_csv_upload(
        self,
        *,
        name: str,
        phone_number_column_name: str,
        file: core.File,
        description: typing.Optional[str] = OMIT,
        identifier_column_name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostAudienceResponse:
        """
        Create a new audience by uploading a CSV file containing phone numbers.
        Only CSV text files are accepted — binary files will produce malformed data.

        **Additional 400 cases:**
        - Duplicate phone numbers in the CSV: `"Some phone numbers in your CSV already exist in this audience. Please remove duplicate entries and try again."`
        - Member limit exceeded: `"Audience cannot exceed X members"`

        Parameters
        ----------
        name : str
            The name of the audience

        phone_number_column_name : str
            The name of the column in the CSV that contains phone numbers

        file : core.File
            See core.File for more documentation

        description : typing.Optional[str]
            Optional description of the audience

        identifier_column_name : typing.Optional[str]
            The name of the column in the CSV that contains identifiers (e.g., names)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostAudienceResponse
            Audience created successfully

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.audience.create_audience_with_csv_upload(
                name="name",
                phone_number_column_name="phoneNumberColumnName",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_audience_with_csv_upload(
            name=name,
            phone_number_column_name=phone_number_column_name,
            file=file,
            description=description,
            identifier_column_name=identifier_column_name,
            request_options=request_options,
        )
        return _response.data

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetAudienceResponse:
        """
        Retrieve a specific audience by its ID.
        Note: if the audience belongs to a different organization, the API returns 404 (not 403) — ownership is deliberately obscured.

        Parameters
        ----------
        id : str
            The unique identifier of the audience

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAudienceResponse
            Successfully retrieved audience

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.audience.get(
                id="60d0fe4f5311236168a109ca",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data

    async def delete_audience(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteAudienceIdResponse:
        """
        Delete a specific audience by its ID. Users can only delete audiences they created.

        **400 is returned if the audience is used by an active campaign:**
        `"can't delete audience, campaign with this audience <id> exists"`
        Remove the campaign first, then retry deletion.

        On success, `data` is always an empty array `[]`.

        Parameters
        ----------
        id : str
            The unique identifier of the audience to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteAudienceIdResponse
            Audience deleted successfully

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.audience.delete_audience(
                id="60d0fe4f5311236168a109ca",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_audience(id, request_options=request_options)
        return _response.data

    async def get_audience_members(
        self,
        id: str,
        *,
        page: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetAudienceIdMembersResponse:
        """
        Retrieve members of a specific audience with pagination support. Users can only access members of audiences they created.

        Parameters
        ----------
        id : str
            The unique identifier of the audience

        page : typing.Optional[int]
            Page number for pagination (default is 1)

        offset : typing.Optional[int]
            Number of items per page (default is 5).
            Note: this parameter is named "offset", not "limit" — sending ?limit=N is silently ignored.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAudienceIdMembersResponse
            Successfully retrieved audience members

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.audience.get_audience_members(
                id="60d0fe4f5311236168a109ca",
                page=1,
                offset=10,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_audience_members(
            id, page=page, offset=offset, request_options=request_options
        )
        return _response.data

    async def add_audience_members(
        self,
        id: str,
        *,
        members: typing.Sequence[typing.Dict[str, typing.Any]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostAudienceIdMembersResponse:
        """
        Add new members to an existing audience.

        Each member object must include a key matching the audience's `phoneNumberColumnName`.
        If it's missing, the API returns 400: `"Each member must have a <phoneNumberColumnName> field"`.
        Adding members that would exceed the audience limit also returns 400.

        Note: if the audience belongs to a different organization, the API returns 404 (not 403).

        Parameters
        ----------
        id : str
            The unique identifier of the audience

        members : typing.Sequence[typing.Dict[str, typing.Any]]
            Array of member objects with dynamic structure based on audience configuration

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostAudienceIdMembersResponse
            Members added successfully

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.audience.add_audience_members(
                id="60d0fe4f5311236168a109ca",
                members=[
                    {
                        "phoneNumber": "+1234567890",
                        "name": "John Doe",
                        "email": "john@example.com",
                    }
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add_audience_members(id, members=members, request_options=request_options)
        return _response.data

    async def delete_audience_members(
        self, id: str, *, member_ids: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteAudienceIdMembersResponse:
        """
        Remove specific members from an audience by their member IDs. Users can only delete members from audiences they created.

        Parameters
        ----------
        id : str
            The unique identifier of the audience

        member_ids : typing.Sequence[str]
            Array of member IDs to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteAudienceIdMembersResponse
            Members deleted successfully

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.audience.delete_audience_members(
                id="60d0fe4f5311236168a109ca",
                member_ids=["60d0fe4f5311236168a109cd"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_audience_members(
            id, member_ids=member_ids, request_options=request_options
        )
        return _response.data

    async def search_audience_members(
        self, id: str, *, query: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> GetAudienceIdMembersSearchResponse:
        """
        Search for members within a specific audience using flexible search parameters. Users can only search members of audiences they created.

        **Search Types:**
        - **General Search** (`query`): Searches across all fields in the audience member data
        - **Field-Specific Search**: Use any field name as a parameter (e.g., `firstName=john`, `phoneNumber=123456`, `email=test@example.com`)

        **Examples:**
        - `?query=john` - General search across all fields
        - `?firstName=john` - Search specifically in firstName field
        - `?phoneNumber=555-1234` - Search specifically in phoneNumber field
        - `?firstName=john&lastName=doe` - Search for members matching both criteria

        **Note:** When using phoneNumber field, do not use quotes around the phone number. You can use either a general search OR field-specific searches, but not both simultaneously.

        Parameters
        ----------
        id : str
            The unique identifier of the audience

        query : typing.Optional[str]
            General search term that searches across all fields in audience member data

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAudienceIdMembersSearchResponse
            Search results returned successfully

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.audience.search_audience_members(
                id="60d0fe4f5311236168a109ca",
                query="john",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search_audience_members(id, query=query, request_options=request_options)
        return _response.data
