# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.serialization import FieldMetadata
from ....core.unchecked_base_model import UncheckedBaseModel


class GetAgentAvatarPresignedUrlResponseData(UncheckedBaseModel):
    presigned_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="presignedUrl"),
        pydantic.Field(alias="presignedUrl", description="S3 pre-signed PUT URL (expires in 300 s)"),
    ] = None
    cdn_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="cdnUrl"),
        pydantic.Field(alias="cdnUrl", description="Final public CDN URL to save on the agent after upload"),
    ] = None
    key: typing.Optional[str] = pydantic.Field(default=None)
    """
    S3 object key
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
