# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawUserClient, RawUserClient
from .types.get_subscription_user_response import GetSubscriptionUserResponse
from .types.get_user_response import GetUserResponse


class UserClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawUserClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawUserClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawUserClient
        """
        return self._raw_client

    def get_user_details(self, *, request_options: typing.Optional[RequestOptions] = None) -> GetUserResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetUserResponse
            Successful response

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.user.get_user_details()
        """
        _response = self._raw_client.get_user_details(request_options=request_options)
        return _response.data

    def get_subscription(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetSubscriptionUserResponse:
        """
        Returns the caller's subscription details (plan ID + plan-tier limits) and
        feature-flag map. Useful for client-side gating of paid features.

        **`limits` is omitted** for the `ENTERPRISE` plan (and for unknown plan IDs) —
        only `features` is returned in those cases.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSubscriptionUserResponse
            Subscription details + limits + features.

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.user.get_subscription()
        """
        _response = self._raw_client.get_subscription(request_options=request_options)
        return _response.data


class AsyncUserClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawUserClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawUserClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawUserClient
        """
        return self._raw_client

    async def get_user_details(self, *, request_options: typing.Optional[RequestOptions] = None) -> GetUserResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetUserResponse
            Successful response

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.user.get_user_details()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_user_details(request_options=request_options)
        return _response.data

    async def get_subscription(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetSubscriptionUserResponse:
        """
        Returns the caller's subscription details (plan ID + plan-tier limits) and
        feature-flag map. Useful for client-side gating of paid features.

        **`limits` is omitted** for the `ENTERPRISE` plan (and for unknown plan IDs) —
        only `features` is returned in those cases.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSubscriptionUserResponse
            Subscription details + limits + features.

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.user.get_subscription()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_subscription(request_options=request_options)
        return _response.data
