# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawAgentVersioningRevisionsClient, RawAgentVersioningRevisionsClient
from .types.diff_agent_versioning_revisions_response import DiffAgentVersioningRevisionsResponse
from .types.get_agent_versioning_revisions_response import GetAgentVersioningRevisionsResponse
from .types.get_history_agent_versioning_revisions_response import GetHistoryAgentVersioningRevisionsResponse
from .types.list_agent_versioning_revisions_response import ListAgentVersioningRevisionsResponse
from .types.restore_agent_versioning_revisions_response import RestoreAgentVersioningRevisionsResponse


class AgentVersioningRevisionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgentVersioningRevisionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAgentVersioningRevisionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgentVersioningRevisionsClient
        """
        return self._raw_client

    def list(
        self,
        id: str,
        branch_id: str,
        *,
        limit: typing.Optional[int] = None,
        skip: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListAgentVersioningRevisionsResponse:
        """
        Paginated list of committed and scanning revisions on this branch, newest first.

        Parameters
        ----------
        id : str
            The agent ID.

        branch_id : str
            The branch ID.

        limit : typing.Optional[int]

        skip : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAgentVersioningRevisionsResponse
            Successful response.

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.agent_versioning_revisions.list(
            id="id",
            branch_id="branchId",
        )
        """
        _response = self._raw_client.list(id, branch_id, limit=limit, skip=skip, request_options=request_options)
        return _response.data

    def get(
        self, id: str, branch_id: str, revision_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetAgentVersioningRevisionsResponse:
        """
        Return a single revision plus its `resolvedConfig` (the fully-merged agent config at that revision).

        Parameters
        ----------
        id : str
            The agent ID.

        branch_id : str
            The branch ID.

        revision_id : str
            The revision ID. Equal to the v1 `versionId` for revisions that were migrated from the v1 model.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAgentVersioningRevisionsResponse
            Successful response.

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.agent_versioning_revisions.get(
            id="id",
            branch_id="branchId",
            revision_id="revisionId",
        )
        """
        _response = self._raw_client.get(id, branch_id, revision_id, request_options=request_options)
        return _response.data

    def get_history(
        self, id: str, branch_id: str, revision_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetHistoryAgentVersioningRevisionsResponse:
        """
        Return the publish trail for a revision: who published it, and the ordered list of prior revisions on this branch with the sections that changed at each step.

        Parameters
        ----------
        id : str
            The agent ID.

        branch_id : str
            The branch ID.

        revision_id : str
            The revision ID. Equal to the v1 `versionId` for revisions that were migrated from the v1 model.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetHistoryAgentVersioningRevisionsResponse
            Successful response.

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.agent_versioning_revisions.get_history(
            id="id",
            branch_id="branchId",
            revision_id="revisionId",
        )
        """
        _response = self._raw_client.get_history(id, branch_id, revision_id, request_options=request_options)
        return _response.data

    def restore(
        self, id: str, branch_id: str, revision_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RestoreAgentVersioningRevisionsResponse:
        """
        Republish an older revision as a new revision at the head of this branch. Restore does not overwrite history; the older revision keeps its ID, and a new revision is committed on top.

        The response mirrors `POST /agent/{id}/branches/{branchId}/draft/publish`: `200 committed` if the scan is synchronous, `202 scanning` if deferred. Only one publish or restore can be in flight per branch at a time.

        Parameters
        ----------
        id : str
            The agent ID.

        branch_id : str
            The branch ID.

        revision_id : str
            The revision ID. Equal to the v1 `versionId` for revisions that were migrated from the v1 model.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RestoreAgentVersioningRevisionsResponse
            Restored synchronously.

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.agent_versioning_revisions.restore(
            id="id",
            branch_id="branchId",
            revision_id="revisionId",
        )
        """
        _response = self._raw_client.restore(id, branch_id, revision_id, request_options=request_options)
        return _response.data

    def diff(
        self, id: str, *, a: str, b: str, request_options: typing.Optional[RequestOptions] = None
    ) -> DiffAgentVersioningRevisionsResponse:
        """
        Compare any two references on this agent and return per-section diffs. Each side (`a` and `b`) is either a `revisionId` or the string `<branchId>:draft` to reference the open draft on a branch. Sides may cross branches. Both references must resolve to configs on the same agent.

        Parameters
        ----------
        id : str
            The agent ID.

        a : str
            Left-hand side. Either a `revisionId` (24-hex ObjectId) or the token `<branchId>:draft`.

        b : str
            Right-hand side. Either a `revisionId` (24-hex ObjectId) or the token `<branchId>:draft`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DiffAgentVersioningRevisionsResponse
            Successful response.

        Examples
        --------
        from smallestai import SmallestAI

        client = SmallestAI(
            api_key="YOUR_API_KEY",
        )
        client.atoms.agent_versioning_revisions.diff(
            id="id",
            a="a",
            b="b",
        )
        """
        _response = self._raw_client.diff(id, a=a, b=b, request_options=request_options)
        return _response.data


class AsyncAgentVersioningRevisionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgentVersioningRevisionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAgentVersioningRevisionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgentVersioningRevisionsClient
        """
        return self._raw_client

    async def list(
        self,
        id: str,
        branch_id: str,
        *,
        limit: typing.Optional[int] = None,
        skip: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListAgentVersioningRevisionsResponse:
        """
        Paginated list of committed and scanning revisions on this branch, newest first.

        Parameters
        ----------
        id : str
            The agent ID.

        branch_id : str
            The branch ID.

        limit : typing.Optional[int]

        skip : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAgentVersioningRevisionsResponse
            Successful response.

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.agent_versioning_revisions.list(
                id="id",
                branch_id="branchId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(id, branch_id, limit=limit, skip=skip, request_options=request_options)
        return _response.data

    async def get(
        self, id: str, branch_id: str, revision_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetAgentVersioningRevisionsResponse:
        """
        Return a single revision plus its `resolvedConfig` (the fully-merged agent config at that revision).

        Parameters
        ----------
        id : str
            The agent ID.

        branch_id : str
            The branch ID.

        revision_id : str
            The revision ID. Equal to the v1 `versionId` for revisions that were migrated from the v1 model.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAgentVersioningRevisionsResponse
            Successful response.

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.agent_versioning_revisions.get(
                id="id",
                branch_id="branchId",
                revision_id="revisionId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, branch_id, revision_id, request_options=request_options)
        return _response.data

    async def get_history(
        self, id: str, branch_id: str, revision_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetHistoryAgentVersioningRevisionsResponse:
        """
        Return the publish trail for a revision: who published it, and the ordered list of prior revisions on this branch with the sections that changed at each step.

        Parameters
        ----------
        id : str
            The agent ID.

        branch_id : str
            The branch ID.

        revision_id : str
            The revision ID. Equal to the v1 `versionId` for revisions that were migrated from the v1 model.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetHistoryAgentVersioningRevisionsResponse
            Successful response.

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.agent_versioning_revisions.get_history(
                id="id",
                branch_id="branchId",
                revision_id="revisionId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_history(id, branch_id, revision_id, request_options=request_options)
        return _response.data

    async def restore(
        self, id: str, branch_id: str, revision_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RestoreAgentVersioningRevisionsResponse:
        """
        Republish an older revision as a new revision at the head of this branch. Restore does not overwrite history; the older revision keeps its ID, and a new revision is committed on top.

        The response mirrors `POST /agent/{id}/branches/{branchId}/draft/publish`: `200 committed` if the scan is synchronous, `202 scanning` if deferred. Only one publish or restore can be in flight per branch at a time.

        Parameters
        ----------
        id : str
            The agent ID.

        branch_id : str
            The branch ID.

        revision_id : str
            The revision ID. Equal to the v1 `versionId` for revisions that were migrated from the v1 model.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RestoreAgentVersioningRevisionsResponse
            Restored synchronously.

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.agent_versioning_revisions.restore(
                id="id",
                branch_id="branchId",
                revision_id="revisionId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.restore(id, branch_id, revision_id, request_options=request_options)
        return _response.data

    async def diff(
        self, id: str, *, a: str, b: str, request_options: typing.Optional[RequestOptions] = None
    ) -> DiffAgentVersioningRevisionsResponse:
        """
        Compare any two references on this agent and return per-section diffs. Each side (`a` and `b`) is either a `revisionId` or the string `<branchId>:draft` to reference the open draft on a branch. Sides may cross branches. Both references must resolve to configs on the same agent.

        Parameters
        ----------
        id : str
            The agent ID.

        a : str
            Left-hand side. Either a `revisionId` (24-hex ObjectId) or the token `<branchId>:draft`.

        b : str
            Right-hand side. Either a `revisionId` (24-hex ObjectId) or the token `<branchId>:draft`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DiffAgentVersioningRevisionsResponse
            Successful response.

        Examples
        --------
        import asyncio

        from smallestai import AsyncSmallestAI

        client = AsyncSmallestAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.atoms.agent_versioning_revisions.diff(
                id="id",
                a="a",
                b="b",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.diff(id, a=a, b=b, request_options=request_options)
        return _response.data
