# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .conversation_item_content_item import ConversationItemContentItem
from .conversation_item_role import ConversationItemRole
from .conversation_item_status import ConversationItemStatus
from .conversation_item_type import ConversationItemType


class ConversationItem(UncheckedBaseModel):
    """
    Carried by most conversation events. The shape is intentionally flat — every field is optional; presence is dictated by `type`.
    """

    id: typing.Optional[str] = None
    type: typing.Optional[ConversationItemType] = None
    role: typing.Optional[ConversationItemRole] = None
    status: typing.Optional[ConversationItemStatus] = None
    content: typing.Optional[typing.List[ConversationItemContentItem]] = None
    call_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    `function_call` / `function_call_output` only.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    `function_call` only.
    """

    arguments: typing.Optional[str] = pydantic.Field(default=None)
    """
    `function_call` only — JSON-encoded argument string.
    """

    output: typing.Optional[str] = pydantic.Field(default=None)
    """
    `function_call_output` only — your tool result.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
