# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel
from .get_voices_waves_response_voices_item_tags import GetVoicesWavesResponseVoicesItemTags


class GetVoicesWavesResponseVoicesItem(UncheckedBaseModel):
    voice_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="voiceId"), pydantic.Field(alias="voiceId", description="Unique Voice ID.")
    ]
    display_name: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="displayName"),
        pydantic.Field(alias="displayName", description="Display name for the voice."),
    ]
    tags: typing.Optional[GetVoicesWavesResponseVoicesItemTags] = pydantic.Field(default=None)
    """
    Tag metadata used to identify the voice's characteristics. Filter on these fields to find voices for a target language, accent, or use case.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
