# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .tts_request_content_filter_action import TtsRequestContentFilterAction


class TtsRequestContentFilter(UncheckedBaseModel):
    """
    Opt-in profanity filter for the submitted text. Off by default;
    passing this object is the only way to turn it on. The filter
    never rewrites your text — it either lets the request through or
    rejects it before synthesis.

    `action: "reject"` returns HTTP 400 with `error_code:
    "CONTENT_FILTER_BLOCKED"`, the `language` checked and a
    `match_count`; the matched terms are never returned or logged.
    `action: "flag"` synthesizes normally and records the match.

    Matching is whole-word, not substring. If no verdict is returned
    the request fails open and the audio is synthesized unfiltered.

    See [Content filter](/models/documentation/text-to-speech-lightning/content-filter).
    """

    enabled: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Must be the literal `true` to enable the filter. Any other value leaves it off.
    """

    action: typing.Optional[TtsRequestContentFilterAction] = pydantic.Field(default=None)
    """
    What happens on a match. `reject` fails the request with HTTP 400; `flag` synthesizes normally and records the match.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
