# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .usage_prompt_tokens_details import UsagePromptTokensDetails


class Usage(UncheckedBaseModel):
    prompt_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total input tokens (cached + uncached).
    """

    completion_tokens: typing.Optional[int] = None
    total_tokens: typing.Optional[int] = None
    prompt_tokens_details: typing.Optional[UsagePromptTokensDetails] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
