# coding: utf-8

"""
    Agent Management API

    API for managing agents, their templates, and call logs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from smallestai.atoms.api.campaigns_api import CampaignsApi


class TestCampaignsApi(unittest.TestCase):
    """CampaignsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CampaignsApi()

    def tearDown(self) -> None:
        pass

    def test_create_campaign(self) -> None:
        """Test case for create_campaign

        Create a campaign
        """
        pass

    def test_delete_campaign(self) -> None:
        """Test case for delete_campaign

        Delete a campaign
        """
        pass

    def test_get_campaign_by_id(self) -> None:
        """Test case for get_campaign_by_id

        Get a campaign
        """
        pass

    def test_get_campaigns(self) -> None:
        """Test case for get_campaigns

        Retrieve all campaigns
        """
        pass

    def test_start_campaign(self) -> None:
        """Test case for start_campaign

        Start a campaign
        """
        pass

    def test_stop_campaign(self) -> None:
        """Test case for stop_campaign

        Stop a campaign
        """
        pass


if __name__ == '__main__':
    unittest.main()
