# coding: utf-8

"""
    Agent Management API

    API for managing agents, their templates, and call logs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from smallestai.atoms.models.get_campaigns_request import GetCampaignsRequest

class TestGetCampaignsRequest(unittest.TestCase):
    """GetCampaignsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCampaignsRequest:
        """Test GetCampaignsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCampaignsRequest`
        """
        model = GetCampaignsRequest()
        if include_optional:
            return GetCampaignsRequest(
                page = 1.337,
                limit = 1.337
            )
        else:
            return GetCampaignsRequest(
        )
        """

    def testGetCampaignsRequest(self):
        """Test GetCampaignsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
