# coding: utf-8

"""
    Agent Management API

    API for managing agents, their templates, and call logs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from smallestai.atoms.api.logs_api import LogsApi


class TestLogsApi(unittest.TestCase):
    """LogsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LogsApi()

    def tearDown(self) -> None:
        pass

    def test_get_conversation(self) -> None:
        """Test case for get_conversation

        Get conversation logs
        """
        pass


if __name__ == '__main__':
    unittest.main()
