# coding: utf-8

"""
    Agent Management API

    API for managing agents, their templates, and call logs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from smallestai.atoms.models.create_agent_from_template_request import CreateAgentFromTemplateRequest

class TestCreateAgentFromTemplateRequest(unittest.TestCase):
    """CreateAgentFromTemplateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAgentFromTemplateRequest:
        """Test CreateAgentFromTemplateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAgentFromTemplateRequest`
        """
        model = CreateAgentFromTemplateRequest()
        if include_optional:
            return CreateAgentFromTemplateRequest(
                agent_name = '',
                agent_description = '',
                template_id = ''
            )
        else:
            return CreateAgentFromTemplateRequest(
                agent_name = '',
                template_id = '',
        )
        """

    def testCreateAgentFromTemplateRequest(self):
        """Test CreateAgentFromTemplateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
