# coding: utf-8

"""
    Agent Management API

    API for managing agents, their templates, and call logs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from smallestai.atoms.models.update_agent200_response import UpdateAgent200Response

class TestUpdateAgent200Response(unittest.TestCase):
    """UpdateAgent200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateAgent200Response:
        """Test UpdateAgent200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateAgent200Response`
        """
        model = UpdateAgent200Response()
        if include_optional:
            return UpdateAgent200Response(
                status = True,
                data = '60d0fe4f5311236168a109ca'
            )
        else:
            return UpdateAgent200Response(
        )
        """

    def testUpdateAgent200Response(self):
        """Test UpdateAgent200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
