# coding: utf-8

"""
    Agent Management API

    API for managing agents, their templates, and call logs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from smallestai.atoms.api.agents_api import AgentsApi

class TestAgentsApi(unittest.TestCase):
    """AgentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AgentsApi()

    def tearDown(self) -> None:
        pass

    def test_create_agent(self) -> None:
        """Test case for create_agent

        Create a new agent
        """
        pass

    def test_delete_agent(self) -> None:
        """Test case for delete_agent

        Delete an agent
        """
        pass

    def test_get_agent_by_id(self) -> None:
        """Test case for get_agent_by_id

        Get agent by ID
        """
        pass

    def test_get_agents(self) -> None:
        """Test case for get_agents

        Get all agents
        """
        pass

    def test_update_agent(self) -> None:
        """Test case for update_agent

        Update an agent
        """
        pass


if __name__ == '__main__':
    unittest.main()
