# coding: utf-8

"""
    Agent Management API

    API for managing agents, their templates, and call logs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from smallestai.atoms.models.get_organization200_response_data_members_inner import GetOrganization200ResponseDataMembersInner

class TestGetOrganization200ResponseDataMembersInner(unittest.TestCase):
    """GetOrganization200ResponseDataMembersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetOrganization200ResponseDataMembersInner:
        """Test GetOrganization200ResponseDataMembersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetOrganization200ResponseDataMembersInner`
        """
        model = GetOrganization200ResponseDataMembersInner()
        if include_optional:
            return GetOrganization200ResponseDataMembersInner(
                id = '',
                user_email = ''
            )
        else:
            return GetOrganization200ResponseDataMembersInner(
        )
        """

    def testGetOrganization200ResponseDataMembersInner(self):
        """Test GetOrganization200ResponseDataMembersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
