# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.serialization import FieldMetadata
from ...types.agent_version import AgentVersion


class GetAgentIdVersionsResponseDataVersionsItem(AgentVersion):
    published_by_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="publishedByName"),
        pydantic.Field(alias="publishedByName", description="Display name of the user who published"),
    ] = None
    activated_by_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="activatedByName"),
        pydantic.Field(alias="activatedByName", description="Display name of the user who activated the version"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
