# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.unchecked_base_model import UncheckedBaseModel
from .get_product_phone_numbers_response_data_item import GetProductPhoneNumbersResponseDataItem


class GetProductPhoneNumbersResponse(UncheckedBaseModel):
    status: typing.Optional[bool] = None
    data: typing.Optional[typing.List[GetProductPhoneNumbersResponseDataItem]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
