# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.unchecked_base_model import UncheckedBaseModel
from ...types.conversation_item import ConversationItem
from .conversation_item_added_type import ConversationItemAddedType


class ConversationItemAdded(UncheckedBaseModel):
    type: typing.Optional[ConversationItemAddedType] = None
    event_id: typing.Optional[str] = None
    previous_item_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of the item immediately preceding this one in the conversation log.
    """

    item: typing.Optional[ConversationItem] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
