# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel
from .agent_telephony_binding_source_kind import AgentTelephonyBindingSourceKind


class AgentTelephonyBinding(UncheckedBaseModel):
    """
    The stored binding record, as returned by the attach endpoints.
    """

    id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="_id"), pydantic.Field(alias="_id")] = (
        None
    )
    agent_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="agentId"), pydantic.Field(alias="agentId")
    ] = None
    source_kind: typing_extensions.Annotated[
        typing.Optional[AgentTelephonyBindingSourceKind],
        FieldMetadata(alias="sourceKind"),
        pydantic.Field(alias="sourceKind"),
    ] = None
    source_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="sourceId"), pydantic.Field(alias="sourceId")
    ] = None
    number: typing.Optional[str] = pydantic.Field(default=None)
    """
    Present on trunk caller-ID bindings only
    """

    created_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ] = None
    updated_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
