# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel


class AgentVersionBlocks(UncheckedBaseModel):
    """
    References to the 13 config section blocks
    """

    workflow_prompt: typing.Optional[str] = None
    workflow_tools: typing.Optional[str] = None
    workflow_graph: typing.Optional[str] = None
    llm: typing.Optional[str] = None
    voice: typing.Optional[str] = None
    language: typing.Optional[str] = None
    call_handling: typing.Optional[str] = None
    detection: typing.Optional[str] = None
    analytics: typing.Optional[str] = None
    timeouts: typing.Optional[str] = None
    audio: typing.Optional[str] = None
    privacy: typing.Optional[str] = None
    widget: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
