# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel
from .agent_caller_id_source_source_kind import AgentCallerIdSourceSourceKind


class AgentCallerIdSource(UncheckedBaseModel):
    binding_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="bindingId"), pydantic.Field(alias="bindingId")
    ] = None
    source_kind: typing_extensions.Annotated[
        typing.Optional[AgentCallerIdSourceSourceKind],
        FieldMetadata(alias="sourceKind"),
        pydantic.Field(alias="sourceKind"),
    ] = None
    source_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="sourceId"), pydantic.Field(alias="sourceId")
    ] = None
    label: typing.Optional[str] = pydantic.Field(default=None)
    """
    The E.164 number this entry dials from
    """

    source_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="sourceName"),
        pydantic.Field(
            alias="sourceName", description='Where the number lives ("Purchased number" or the trunk\'s name)'
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
