# This file was auto-generated by Fern from our API Definition.

import typing

AgentDtoWidgetConfigPosition = typing.Union[
    typing.Literal["bottom-right", "bottom-left", "top-right", "top-left"], typing.Any
]
