# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel
from .agent_dto_background_sound import AgentDtoBackgroundSound
from .agent_dto_config_source import AgentDtoConfigSource
from .agent_dto_language import AgentDtoLanguage
from .agent_dto_pre_call_api import AgentDtoPreCallApi
from .agent_dto_resolved_config import AgentDtoResolvedConfig
from .agent_dto_slm_model import AgentDtoSlmModel
from .agent_dto_synthesizer import AgentDtoSynthesizer
from .agent_dto_versioned_workflow import AgentDtoVersionedWorkflow
from .workflow_type import WorkflowType


class AgentDto(UncheckedBaseModel):
    id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="_id"), pydantic.Field(alias="_id", description="The ID of the agent")
    ] = None
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the agent
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    The description of the agent
    """

    background_sound: typing_extensions.Annotated[
        typing.Optional[AgentDtoBackgroundSound],
        FieldMetadata(alias="backgroundSound"),
        pydantic.Field(
            alias="backgroundSound",
            description="Ambient background sound during calls. Options: '' (none), 'office', 'cafe', 'call_center', 'static'.",
        ),
    ] = None
    organization: typing.Optional[str] = pydantic.Field(default=None)
    """
    The organization ID of the agent
    """

    workflow_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="workflowId"),
        pydantic.Field(alias="workflowId", description="The workflow ID of the agent"),
    ] = None
    workflow_type: typing_extensions.Annotated[
        typing.Optional[WorkflowType],
        FieldMetadata(alias="workflowType"),
        pydantic.Field(alias="workflowType", description="The type of workflow used by the agent"),
    ] = None
    created_by: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="createdBy"),
        pydantic.Field(alias="createdBy", description="The user ID of the user who created the agent"),
    ] = None
    global_knowledge_base_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="globalKnowledgeBaseId"),
        pydantic.Field(alias="globalKnowledgeBaseId", description="The global knowledge base ID of the agent"),
    ] = None
    language: typing.Optional[AgentDtoLanguage] = pydantic.Field(default=None)
    """
    The language configuration of the agent
    """

    synthesizer: typing.Optional[AgentDtoSynthesizer] = pydantic.Field(default=None)
    """
    The synthesizer (TTS) configuration of the agent
    """

    slm_model: typing_extensions.Annotated[
        typing.Optional[AgentDtoSlmModel],
        FieldMetadata(alias="slmModel"),
        pydantic.Field(
            alias="slmModel",
            description="The LLM model to use for the agent. LLM model will be used to generate the response and take decisions based on the user's query.",
        ),
    ] = None
    default_variables: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Any]],
        FieldMetadata(alias="defaultVariables"),
        pydantic.Field(
            alias="defaultVariables",
            description="The default variables to use for the agent. These variables will be used if no variables are provided when initiating a conversation with the agent.",
        ),
    ] = None
    pre_call_api: typing_extensions.Annotated[
        typing.Optional[AgentDtoPreCallApi],
        FieldMetadata(alias="preCallAPI"),
        pydantic.Field(
            alias="preCallAPI",
            description="Configuration for an API call to be made before the call starts. The response variables can be injected into the agent's prompt.",
        ),
    ] = None
    created_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="The date and time when the agent was created"),
    ] = None
    updated_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="updatedAt"),
        pydantic.Field(alias="updatedAt", description="The date and time when the agent was last updated"),
    ] = None
    avatar_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="avatarUrl"),
        pydantic.Field(alias="avatarUrl", description="URL of the agent's avatar image"),
    ] = None
    first_message: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="firstMessage"),
        pydantic.Field(
            alias="firstMessage", description="The opening message spoken by the agent at the start of a call"
        ),
    ] = None
    allow_interruptions: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="allowInterruptions"),
        pydantic.Field(
            alias="allowInterruptions", description="Whether the agent can be interrupted mid-speech by the caller"
        ),
    ] = None
    wait_for_user_to_speak_first: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="waitForUserToSpeakFirst"),
        pydantic.Field(
            alias="waitForUserToSpeakFirst",
            description="When true, the agent waits for the caller to speak before responding",
        ),
    ] = None
    total_calls: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="totalCalls"),
        pydantic.Field(alias="totalCalls", description="Total number of calls made with this agent"),
    ] = None
    transcriber_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="transcriberType"),
        pydantic.Field(alias="transcriberType", description="The speech-to-text engine used for transcription"),
    ] = None
    global_prompt: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="globalPrompt"),
        pydantic.Field(alias="globalPrompt", description="A global system prompt prepended to all agent interactions"),
    ] = None
    archived: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the agent has been archived. Archived agents are excluded from default listings.
    """

    archived_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="archivedAt"),
        pydantic.Field(alias="archivedAt", description="The date and time when the agent was archived"),
    ] = None
    is_locked: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="isLocked"),
        pydantic.Field(alias="isLocked", description="Whether the agent is locked and cannot be edited"),
    ] = None
    active_version_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="activeVersionId"),
        pydantic.Field(
            alias="activeVersionId", description="ID of the currently-active published version. Matches `versionId`."
        ),
    ] = None
    version_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="versionId"),
        pydantic.Field(alias="versionId", description="Alias for `activeVersionId`."),
    ] = None
    resolved_config: typing_extensions.Annotated[
        typing.Optional[AgentDtoResolvedConfig],
        FieldMetadata(alias="_resolvedConfig"),
        pydantic.Field(
            alias="_resolvedConfig",
            description="The resolved config of the target version, merged into a flat shape. Not returned in\nlist responses (`GET /agent`). Only populated in single-agent responses\n(`GET /agent/{id}`) when the agent has a published, activated version.\nCan contain up to ~30 fields depending on which config sections are set.",
        ),
    ] = None
    config_source: typing_extensions.Annotated[
        typing.Optional[AgentDtoConfigSource],
        FieldMetadata(alias="_configSource"),
        pydantic.Field(
            alias="_configSource",
            description="Only present when `?draftId` or `?versionId` query params are used.\nIndicates which config source was resolved into `_resolvedConfig`.",
        ),
    ] = None
    versioned_workflow: typing_extensions.Annotated[
        typing.Optional[AgentDtoVersionedWorkflow],
        FieldMetadata(alias="_versionedWorkflow"),
        pydantic.Field(
            alias="_versionedWorkflow",
            description="**Deprecated — internal use only.** Legacy field present whenever `_resolvedConfig` is populated.\nMirrors a subset of `_resolvedConfig` (`prompt`, `tools`, `workflowGraph`). Kept for backward\ncompatibility with existing frontend code. Ignore in new integrations.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
