# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel
from .prompt_score import PromptScore
from .revision_pending_publish import RevisionPendingPublish
from .revision_security_check import RevisionSecurityCheck
from .revision_status import RevisionStatus
from .version_blocks import VersionBlocks


class Revision(UncheckedBaseModel):
    """
    An `AgentVersion` document. Represents either a committed revision (`status: published`, with `branch` + `revisionNumber`) or an in-progress draft revision (`status: draft`, with `draftId` + `draftRevision`). Fields that do not apply to a given row are `null`.
    """

    id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="_id"), pydantic.Field(alias="_id")] = (
        None
    )
    agent: typing.Optional[str] = None
    status: typing.Optional[RevisionStatus] = None
    branch: typing.Optional[str] = pydantic.Field(default=None)
    """
    Owning branch (v2). `null` on legacy rows until backfilled.
    """

    revision_number: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="revisionNumber"),
        pydantic.Field(
            alias="revisionNumber", description="Monotonic per-branch commit number. Only set on committed rows."
        ),
    ] = None
    version_number: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="versionNumber"),
        pydantic.Field(
            alias="versionNumber",
            description="Legacy v1 published-version number. `null` for branch revisions and drafts.",
        ),
    ] = None
    label: typing.Optional[str] = None
    description: typing.Optional[str] = None
    is_pinned: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="isPinned"), pydantic.Field(alias="isPinned")
    ] = None
    published_by: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="publishedBy"), pydantic.Field(alias="publishedBy")
    ] = None
    published_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="publishedAt"), pydantic.Field(alias="publishedAt")
    ] = None
    published_by_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="publishedByName"),
        pydantic.Field(alias="publishedByName", description="Display name of the publisher. `null` when unresolvable."),
    ] = None
    restored_from_label: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="restoredFromLabel"),
        pydantic.Field(
            alias="restoredFromLabel",
            description="On a commit produced by restore, the label of the revision it copied.",
        ),
    ] = None
    draft_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="draftId"), pydantic.Field(alias="draftId")
    ] = None
    draft_name: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="draftName"), pydantic.Field(alias="draftName")
    ] = None
    draft_revision: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="draftRevision"), pydantic.Field(alias="draftRevision")
    ] = None
    source_version_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="sourceVersionId"), pydantic.Field(alias="sourceVersionId")
    ] = None
    blocks: typing.Optional[VersionBlocks] = None
    workflow_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="workflowType"),
        pydantic.Field(alias="workflowType", description="The `WorkflowType` enum for this revision."),
    ] = None
    parent_version: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="parentVersion"), pydantic.Field(alias="parentVersion")
    ] = None
    is_active: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="isActive"), pydantic.Field(alias="isActive")
    ] = None
    activated_by: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="activatedBy"), pydantic.Field(alias="activatedBy")
    ] = None
    activated_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="activatedAt"), pydantic.Field(alias="activatedAt")
    ] = None
    security_check: typing_extensions.Annotated[
        typing.Optional[RevisionSecurityCheck],
        FieldMetadata(alias="securityCheck"),
        pydantic.Field(alias="securityCheck", description="Populated after publish. `null` on pre-feature versions."),
    ] = None
    pending_publish: typing_extensions.Annotated[
        typing.Optional[RevisionPendingPublish],
        FieldMetadata(alias="pendingPublish"),
        pydantic.Field(alias="pendingPublish", description="Set while a publish is armed against this draft revision."),
    ] = None
    restored_from_revision_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="restoredFromRevisionId"),
        pydantic.Field(
            alias="restoredFromRevisionId", description="On a commit produced by restore, the revision it copied."
        ),
    ] = None
    source_draft_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="sourceDraftId"), pydantic.Field(alias="sourceDraftId")
    ] = None
    prompt_score: typing_extensions.Annotated[
        typing.Optional[PromptScore], FieldMetadata(alias="promptScore"), pydantic.Field(alias="promptScore")
    ] = None
    prompt_score_stale: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="promptScoreStale"), pydantic.Field(alias="promptScoreStale")
    ] = None
    created_by: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="createdBy"), pydantic.Field(alias="createdBy")
    ] = None
    created_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ] = None
    updated_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
