# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel
from .tool import Tool


class SinglePromptConfig(UncheckedBaseModel):
    """
    Configuration for single prompt workflow type
    """

    prompt: str = pydantic.Field()
    """
    The main prompt that defines the agent's behavior and responses
    """

    tools: typing.Optional[typing.List[Tool]] = pydantic.Field(default=None)
    """
    Array of tools/functions available to the agent during conversations.
    Five tool types are supported: `end_call`, `transfer_call`, `api_call`,
    `extract_dynamic_variables`, and `knowledge_base_search`. Each type has its
    own required fields — see `Tool` schema.
    """

    tool_refs: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="toolRefs"),
        pydantic.Field(
            alias="toolRefs",
            description="Optional. References to reusable tools in the org Tools library (see\n`POST /tool`), by their `toolId`. At serve time the referenced tools are\nexpanded inline and merged with `tools[]` (inline wins on a name conflict),\nthen `toolRefs` is stripped, so the runtime sees a normal `tools[]`.\nAttach a tool by adding its id here; detach by removing it. Additive and\noptional — omit for unchanged behavior.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
